/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Lote;
import Modelo.Propiedad;
import controlador.ControladorPropiedad;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sara
 */
public class ConsultaBienes extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaBienes
     */
    public ConsultaBienes() {
        initComponents();
        //show_user();
    }
    
   /* public ArrayList<Lote> propiedadList(){
        
        ArrayList<Lote> propiedadList = new ArrayList<>();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             String url = "jdbc:sqlserver://LENOVO-U430:1433;databaseName=propiedades;user=admin;password=1234";
             Connection con = DriverManager.getConnection(url);
             
             String query1="SELECT * FROM Lote";
             
             Statement st= con.createStatement();
             ResultSet rs = st.executeQuery(query1); 
             
             Lote prop;
             while(rs.next()){
                  prop= new Lote(rs.getInt("numFinca"), rs.getInt("areaTerreno"),
                          rs.getInt("valorMetro"), rs.getInt("valorFiscal"), rs.getString("ubicacion"), rs.getInt("idProvincia"), rs.getInt("idCanton"), rs.getInt("idDistrito"), rs.getString("senas"));
             propiedadList.add(prop);
             }
             
             
             

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return propiedadList;
    }
    
    public void show_user(){
        ArrayList<Lote> list = propiedadList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Propiedad.getModel();
        Object[] row = new Object[0];
        
        for(int i =0 ; i< list.size(); i++){
            row[0]= list.get(i).getNumFinca();
            //row[1]= list.get(i).getAreaTerreno();
            //row[2]= list.get(i).getValorMetro2();
            //row[3]= list.get(i).getValorFiscal();
            //row[4]= list.get(i).getUbicacion();
            
            model.addRow(row);
           
        }
    }**/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Propiedad = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cboxProvincia = new javax.swing.JComboBox<>();
        cboxTipo = new javax.swing.JComboBox<>();
        cboxModalidad = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sliderMinimo = new javax.swing.JSlider();
        sliderMaximo = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMin = new javax.swing.JLabel();
        txtMax = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnDetallesPropiedad = new javax.swing.JButton();
        btnBuscarPropiedades = new javax.swing.JButton();
        btnFicha = new javax.swing.JButton();
        btnMostrarInteres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Display_Propiedad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numFinca", "areaTerreno", "valorMetro", "valorFiscal", "ubicacion", "idProvincia", "idCanton", "idDistrito", "senas"
            }
        ));
        jScrollPane1.setViewportView(jTable_Display_Propiedad);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido!");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField1.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jTextField1.setText("Buscar propiedad :");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        cboxProvincia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cboxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Provincia", "Alajuela", "Cartago", "Guanacaste", "Heredia", "Limon", "Puntarenas", "San Jose" }));

        cboxTipo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Apartamento", "Casa", "Centro Comercial", "Lote", "" }));
        cboxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoActionPerformed(evt);
            }
        });

        cboxModalidad.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cboxModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modalidad", "Venta", "Alquiler" }));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField3.setText("Rango de precio");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Minimo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Maximo");

        sliderMinimo.setMajorTickSpacing(5000);
        sliderMinimo.setMaximum(20000);
        sliderMinimo.setMinimum(5000);
        sliderMinimo.setMinorTickSpacing(1000);
        sliderMinimo.setPaintLabels(true);
        sliderMinimo.setPaintTicks(true);
        sliderMinimo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMinimoStateChanged(evt);
            }
        });

        sliderMaximo.setMajorTickSpacing(20000);
        sliderMaximo.setMaximum(150000);
        sliderMaximo.setMinimum(30000);
        sliderMaximo.setMinorTickSpacing(10000);
        sliderMaximo.setPaintLabels(true);
        sliderMaximo.setPaintTicks(true);
        sliderMaximo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMaximoStateChanged(evt);
            }
        });

        jLabel6.setText("Desde:");

        jLabel7.setText("Hasta:");

        txtMin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtMax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVolver.setText("Volver");

        btnDetallesPropiedad.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        btnDetallesPropiedad.setText("Ver detalles de propiedad");
        btnDetallesPropiedad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDetallesPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesPropiedadActionPerformed(evt);
            }
        });

        btnBuscarPropiedades.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBuscarPropiedades.setText("BUSCAR PROPIEDADES");
        btnBuscarPropiedades.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPropiedadesActionPerformed(evt);
            }
        });

        btnFicha.setText("Solicitar Ficha de Propiedad");
        btnFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaActionPerformed(evt);
            }
        });

        btnMostrarInteres.setText("Me interesa esta propiedad");
        btnMostrarInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInteresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(jLabel4)))
                        .addGap(209, 209, 209)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVolver)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sliderMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(sliderMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDetallesPropiedad)
                                .addGap(37, 37, 37)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(cboxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232)
                        .addComponent(cboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboxModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscarPropiedades)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMostrarInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(269, 269, 269))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sliderMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnBuscarPropiedades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnFicha)
                .addGap(36, 36, 36)
                .addComponent(btnMostrarInteres)
                .addGap(89, 89, 89)
                .addComponent(btnDetallesPropiedad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetallesPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesPropiedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetallesPropiedadActionPerformed

    private void btnBuscarPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPropiedadesActionPerformed
        // TODO add your handling code here:
        txtMin.setText("$"+ sliderMinimo.getValue());
        txtMax.setText("$"+ sliderMaximo.getValue());
        
        int precioMax= sliderMaximo.getValue();
        int precioMin= sliderMinimo.getValue();
        
        int ProvinciaID = cboxProvincia.getSelectedIndex();
        
        int ModalidadID= cboxModalidad.getSelectedIndex();
        int TipoID= cboxTipo.getSelectedIndex();    
        String modalidad= cboxModalidad.getSelectedItem().toString();
        String tipo = cboxTipo.getSelectedItem().toString();  
                 
        if (ProvinciaID != 0 && ModalidadID != 0 && TipoID!= 0){            
            //         
            ControladorPropiedad con = new ControladorPropiedad();
            
            //con.consultarPropiedades(ProvinciaID, tipo, modalidad, precioMin, precioMax);
            
            
            System.out.println("buscar id provincia= " + ProvinciaID+ "precio minimo= "+ precioMin + "PrecioMax= " + precioMax);
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Seleccione los criterios de busqueda!",
      "Hey!", JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_btnBuscarPropiedadesActionPerformed

    private void sliderMinimoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMinimoStateChanged
        // TODO add your handling code here:
        txtMin.setText("$"+ sliderMinimo.getValue());

    }//GEN-LAST:event_sliderMinimoStateChanged

    private void btnMostrarInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInteresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarInteresActionPerformed

    private void btnFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFichaActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void cboxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTipoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void sliderMaximoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMaximoStateChanged
        // TODO add your handling code here:
        txtMax.setText("$"+ sliderMaximo.getValue());
    }//GEN-LAST:event_sliderMaximoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaBienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaBienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaBienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaBienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaBienes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarPropiedades;
    public javax.swing.JButton btnDetallesPropiedad;
    private javax.swing.JButton btnFicha;
    private javax.swing.JButton btnMostrarInteres;
    private javax.swing.JButton btnVolver;
    public javax.swing.JComboBox<String> cboxModalidad;
    private javax.swing.JComboBox<String> cboxProvincia;
    private javax.swing.JComboBox<String> cboxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Propiedad;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JSlider sliderMaximo;
    private javax.swing.JSlider sliderMinimo;
    private javax.swing.JLabel txtMax;
    private javax.swing.JLabel txtMin;
    // End of variables declaration//GEN-END:variables
}
