/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Lote;
import Modelo.Propiedad;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sara
 */
public class ConsultaBienes extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaBienes
     */
    public ConsultaBienes() {
        initComponents();
        show_user();
    }
    
    public ArrayList<Lote> propiedadList(){
        ArrayList<Lote> propiedadList = new ArrayList<>();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             String url = "jdbc:sqlserver://LENOVO-U430:1433;databaseName=propiedades;user=Sara;password=1234";
             Connection con = DriverManager.getConnection(url);
             
             String query1="SELECT * FROM Lote";
             
             Statement st= con.createStatement();
             ResultSet rs = st.executeQuery(query1); 
             
             Lote prop;
             while(rs.next()){
                  prop= new Lote(rs.getInt("numFinca"), rs.getInt("areaTerreno"),
                          rs.getInt("valorMetro"), rs.getInt("valorFiscal"), rs.getString("ubicacion"), rs.getInt("idProvincia"), rs.getInt("idCanton"), rs.getInt("idDistrito"), rs.getString("senas"));
             propiedadList.add(prop);
             }
             
             
             

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return propiedadList;
    }
    
    public void show_user(){
        ArrayList<Lote> list = propiedadList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Propiedad.getModel();
        Object[] row = new Object[4];
        
        for(int i =0 ; i< list.size(); i++){
            row[0]= list.get(i).getNumFinca();
            row[1]= list.get(i).getAreaTerreno();
            row[2]= list.get(i).getValorMetro2();
            row[3]= list.get(i).getValorFiscal();
            row[4]= list.get(i).getUbicacion();
            
            model.addRow(row);
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Propiedad = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Display_Propiedad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numFinca", "areaTerreno", "valorMetro", "valorFiscal", "ubicacion", "idProvincia", "idCanton", "idDistrito", "senas"
            }
        ));
        jScrollPane1.setViewportView(jTable_Display_Propiedad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaBienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaBienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaBienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaBienes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaBienes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Propiedad;
    // End of variables declaration//GEN-END:variables
}
