
package Vista;

import Animacion.Animacion;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GestionCatalogoFrame extends javax.swing.JFrame {

    public GestionCatalogoFrame() {
        initComponents();                       
        //cargar_cbxcategorias();
        //cargar_cbxproductoscentral();
    }
    public String sede;
    public String tipo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprincipal = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaLotes = new javax.swing.JTable();
        lblModalidad = new javax.swing.JLabel();
        lblNumFinca = new javax.swing.JLabel();
        lblAreaTerreno = new javax.swing.JLabel();
        lblValorFiscal = new javax.swing.JLabel();
        txtNumFincaGestionLotes = new javax.swing.JTextField();
        txtAreaTerrenoGestionLotes = new javax.swing.JTextField();
        txtValorFiscalGestionLotes = new javax.swing.JTextField();
        txtModalidadGestionLotes = new javax.swing.JTextField();
        lblValorMetro2 = new javax.swing.JLabel();
        txtValorMetro2GestionLotes = new javax.swing.JTextField();
        btnModificarGestionLotes = new javax.swing.JButton();
        btnSeleccionarGestionLotes = new javax.swing.JButton();
        btnVerCasas = new javax.swing.JButton();
        btnVolverGestionLotes = new javax.swing.JButton();
        btnEliminarGestionLotes = new javax.swing.JButton();
        MostrarVentasPorMes_GUI = new javax.swing.JPanel();
        btnVolverGestionCasas = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCasas = new javax.swing.JTable();
        btnLimpiarGestionCasas = new javax.swing.JToggleButton();
        lblTitulo1 = new javax.swing.JLabel();
        txtAreaConstruccionGestionCasas = new javax.swing.JTextField();
        lblAreaTerreno1 = new javax.swing.JLabel();
        lblAreaConstruccion = new javax.swing.JLabel();
        lblValorFiscal1 = new javax.swing.JLabel();
        txtCantidadNivelesGestionCasas = new javax.swing.JTextField();
        lblCantNiveles = new javax.swing.JLabel();
        txtNumFincaGestionCasas = new javax.swing.JTextField();
        txtAreaTerrenoGestionCasas = new javax.swing.JTextField();
        txtValorMetro2GestionCasas = new javax.swing.JTextField();
        txtValorFiscalGestionCasas = new javax.swing.JTextField();
        lblNumFinca1 = new javax.swing.JLabel();
        lblValorMetro3 = new javax.swing.JLabel();
        lblEstilo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        txtAnioConstruccion = new javax.swing.JTextField();
        lblAñoConstruccion = new javax.swing.JLabel();
        lblModalidad1 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        txtEstiloConstruccionGestionCasas = new javax.swing.JTextField();
        txtModalidadGestionCasas = new javax.swing.JTextField();
        btnSeleccionarGestionCasas = new javax.swing.JToggleButton();
        btnModificarGestionCasas = new javax.swing.JToggleButton();
        btnEliminarGestionCasas = new javax.swing.JToggleButton();
        btnVerApartamentos = new javax.swing.JToggleButton();
        Admin_GUI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolverGestionApartamentos = new javax.swing.JToggleButton();
        btnAdminLimpiar1 = new javax.swing.JToggleButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaApartamentos = new javax.swing.JTable();
        txtAreaConstruccionGestionCasas1 = new javax.swing.JTextField();
        lblAreaTerreno2 = new javax.swing.JLabel();
        lblAreaConstruccion1 = new javax.swing.JLabel();
        lblValorFiscal2 = new javax.swing.JLabel();
        txtCantidadNivelesGestionCasas1 = new javax.swing.JTextField();
        lblCantNiveles1 = new javax.swing.JLabel();
        txtNumFincaGestionCasas1 = new javax.swing.JTextField();
        txtAreaTerrenoGestionCasas1 = new javax.swing.JTextField();
        txtValorMetro2GestionCasas1 = new javax.swing.JTextField();
        txtValorFiscalGestionCasas1 = new javax.swing.JTextField();
        lblNumFinca2 = new javax.swing.JLabel();
        lblValorMetro4 = new javax.swing.JLabel();
        lblEstilo1 = new javax.swing.JLabel();
        txtAnioConstruccion1 = new javax.swing.JTextField();
        lblAñoConstruccion1 = new javax.swing.JLabel();
        lblModalidad2 = new javax.swing.JLabel();
        txtColor1 = new javax.swing.JTextField();
        txtEstiloConstruccionGestionCasas1 = new javax.swing.JTextField();
        txtModalidadGestionCasas1 = new javax.swing.JTextField();
        lblEstilo2 = new javax.swing.JLabel();
        btnVerCentrosComerciales = new javax.swing.JToggleButton();
        btnSeleccionarGestionApartamentos = new javax.swing.JToggleButton();
        btnModificarGestionApartamentos = new javax.swing.JToggleButton();
        btnEliminarGestionApartamentos = new javax.swing.JToggleButton();
        MostrarTop3Gerente_GUI = new javax.swing.JPanel();
        btnMostrarTop3Volver1 = new javax.swing.JToggleButton();
        jLabel24 = new javax.swing.JLabel();
        txttopfechafin = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txttopfechainicio = new javax.swing.JTextField();
        btnMostrarTop3Consultar = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablatop3clientes = new javax.swing.JTable();
        MostrarVentasPorProductoGerente_GUI = new javax.swing.JPanel();
        btnMostrarVentasPorProductoConsultar = new javax.swing.JToggleButton();
        cboxMostrarProductosGerente = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbxcon2gertienda = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtcon2gerinicio = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtcon2gerfin = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnMostrarVentasPorTiendaVolver1 = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablacon2ger = new javax.swing.JTable();
        MostrarVentasPorTiendaGerente_GUI = new javax.swing.JPanel();
        btnMostrarVentasPorTiendaVolver = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtcon1gerentefin = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtcon1gerenteinicio = new javax.swing.JTextField();
        cboxtiendacon1gerente = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        btnVentasPorTiendaConsultar = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablacon1gerente = new javax.swing.JTable();
        PedidoPorRangoFechas_GUI = new javax.swing.JPanel();
        btnPedidoPorRangoFechasVolver = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtfechainicio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtfechafin = new javax.swing.JTextField();
        btnPedidoPorRangoFechaConsultar = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaconsulta2 = new javax.swing.JTable();
        btnPedidoPorRangoLimpiar1 = new javax.swing.JToggleButton();
        Gerente_GUI = new javax.swing.JPanel();
        btnGerenteVolver = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGerenteMostrarVentas = new javax.swing.JToggleButton();
        btnGerenteMostrarVentasPorProducto = new javax.swing.JToggleButton();
        btnGerenteMostrarTop3Clientes = new javax.swing.JToggleButton();
        InsertarVentaGUI = new javax.swing.JPanel();
        btnInsertarVentanaVolver = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxcliente = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtfechaenvioinsertar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboxproducto = new javax.swing.JComboBox<>();
        cboxempleado = new javax.swing.JComboBox<>();
        btnGenerarVenta = new javax.swing.JToggleButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtcantidad1 = new javax.swing.JTextField();
        txtfechaordeninsertar = new javax.swing.JTextField();
        txtrequireddateinsertar = new javax.swing.JTextField();
        cbxestado = new javax.swing.JComboBox<>();
        txtdescuentoinsertar = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtprecioventainsertar = new javax.swing.JTextField();
        txtiditeminsertar = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprincipal.setMinimumSize(new java.awt.Dimension(850, 560));
        panelprincipal.setName(""); // NOI18N
        panelprincipal.setPreferredSize(new java.awt.Dimension(850, 560));
        panelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setPreferredSize(new java.awt.Dimension(850, 560));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestion de Lotes");
        Login.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 200, 40));

        tablaLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(tablaLotes);

        Login.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 460, 220));

        lblModalidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModalidad.setText("Modalidad");
        Login.add(lblModalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        lblNumFinca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumFinca.setText("Numero de Finca");
        Login.add(lblNumFinca, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        lblAreaTerreno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaTerreno.setText("Area del terreno");
        Login.add(lblAreaTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        lblValorFiscal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorFiscal.setText("Valor Fiscal");
        Login.add(lblValorFiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));
        Login.add(txtNumFincaGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 150, 30));

        txtAreaTerrenoGestionLotes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Login.add(txtAreaTerrenoGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 150, 30));

        txtValorFiscalGestionLotes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorFiscalGestionLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorFiscalGestionLotesActionPerformed(evt);
            }
        });
        Login.add(txtValorFiscalGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 150, 30));

        txtModalidadGestionLotes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModalidadGestionLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModalidadGestionLotesActionPerformed(evt);
            }
        });
        Login.add(txtModalidadGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 150, 30));

        lblValorMetro2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorMetro2.setText("Valor por metro cuadrado");
        Login.add(lblValorMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        txtValorMetro2GestionLotes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Login.add(txtValorMetro2GestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 80, 30));

        btnModificarGestionLotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificarGestionLotes.setText("Modificar");
        Login.add(btnModificarGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, 30));

        btnSeleccionarGestionLotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSeleccionarGestionLotes.setText("Seleccionar");
        Login.add(btnSeleccionarGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 30));

        btnVerCasas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVerCasas.setText("Ver Casas");
        btnVerCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCasasActionPerformed(evt);
            }
        });
        Login.add(btnVerCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 370, 100, 30));

        btnVolverGestionLotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVolverGestionLotes.setText("Volver");
        btnVolverGestionLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverGestionLotesActionPerformed(evt);
            }
        });
        Login.add(btnVolverGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 90, 30));

        btnEliminarGestionLotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarGestionLotes.setText("Eliminar");
        Login.add(btnEliminarGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 100, 30));

        panelprincipal.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 560));
        Login.getAccessibleContext().setAccessibleName("");

        MostrarVentasPorMes_GUI.setMinimumSize(new java.awt.Dimension(850, 560));
        MostrarVentasPorMes_GUI.setPreferredSize(new java.awt.Dimension(850, 560));
        MostrarVentasPorMes_GUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverGestionCasas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVolverGestionCasas.setText("Volver");
        btnVolverGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverGestionCasasActionPerformed(evt);
            }
        });
        MostrarVentasPorMes_GUI.add(btnVolverGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        tablaCasas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCasas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tablaCasas);

        MostrarVentasPorMes_GUI.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 440, 270));

        btnLimpiarGestionCasas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpiarGestionCasas.setText("Limpiar");
        MostrarVentasPorMes_GUI.add(btnLimpiarGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        lblTitulo1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Gestion de Casas");
        MostrarVentasPorMes_GUI.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 200, 40));

        txtAreaConstruccionGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAreaConstruccionGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaConstruccionGestionCasasActionPerformed(evt);
            }
        });
        MostrarVentasPorMes_GUI.add(txtAreaConstruccionGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 120, -1));

        lblAreaTerreno1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaTerreno1.setText("Area del terreno");
        MostrarVentasPorMes_GUI.add(lblAreaTerreno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        lblAreaConstruccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaConstruccion.setText("Area de Construccion");
        MostrarVentasPorMes_GUI.add(lblAreaConstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        lblValorFiscal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorFiscal1.setText("Valor Fiscal");
        MostrarVentasPorMes_GUI.add(lblValorFiscal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        txtCantidadNivelesGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadNivelesGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadNivelesGestionCasasActionPerformed(evt);
            }
        });
        MostrarVentasPorMes_GUI.add(txtCantidadNivelesGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 120, -1));

        lblCantNiveles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantNiveles.setText("Cantidad de Niveles");
        MostrarVentasPorMes_GUI.add(lblCantNiveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        txtNumFincaGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFincaGestionCasasActionPerformed(evt);
            }
        });
        MostrarVentasPorMes_GUI.add(txtNumFincaGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 120, -1));

        txtAreaTerrenoGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MostrarVentasPorMes_GUI.add(txtAreaTerrenoGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 120, -1));

        txtValorMetro2GestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MostrarVentasPorMes_GUI.add(txtValorMetro2GestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 120, -1));

        txtValorFiscalGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorFiscalGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorFiscalGestionCasasActionPerformed(evt);
            }
        });
        MostrarVentasPorMes_GUI.add(txtValorFiscalGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 120, -1));

        lblNumFinca1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumFinca1.setText("Numero de Finca");
        MostrarVentasPorMes_GUI.add(lblNumFinca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        lblValorMetro3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorMetro3.setText("Valor por metro cuadrado");
        MostrarVentasPorMes_GUI.add(lblValorMetro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        lblEstilo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstilo.setText("Estilo Construccion");
        MostrarVentasPorMes_GUI.add(lblEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        lblColor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblColor.setText("Color");
        MostrarVentasPorMes_GUI.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        txtAnioConstruccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnioConstruccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioConstruccionActionPerformed(evt);
            }
        });
        MostrarVentasPorMes_GUI.add(txtAnioConstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 120, -1));

        lblAñoConstruccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAñoConstruccion.setText("Año de Construcción");
        MostrarVentasPorMes_GUI.add(lblAñoConstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        lblModalidad1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModalidad1.setText("Modalidad");
        MostrarVentasPorMes_GUI.add(lblModalidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        txtColor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        MostrarVentasPorMes_GUI.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 120, -1));

        txtEstiloConstruccionGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstiloConstruccionGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstiloConstruccionGestionCasasActionPerformed(evt);
            }
        });
        MostrarVentasPorMes_GUI.add(txtEstiloConstruccionGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 120, -1));

        txtModalidadGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModalidadGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModalidadGestionCasasActionPerformed(evt);
            }
        });
        MostrarVentasPorMes_GUI.add(txtModalidadGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 120, -1));

        btnSeleccionarGestionCasas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSeleccionarGestionCasas.setText("Seleccionar");
        MostrarVentasPorMes_GUI.add(btnSeleccionarGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        btnModificarGestionCasas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnModificarGestionCasas.setText("Modificar");
        MostrarVentasPorMes_GUI.add(btnModificarGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        btnEliminarGestionCasas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminarGestionCasas.setText("Eliminar");
        MostrarVentasPorMes_GUI.add(btnEliminarGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        btnVerApartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVerApartamentos.setText("Ver Apartamentos");
        btnVerApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerApartamentosActionPerformed(evt);
            }
        });
        MostrarVentasPorMes_GUI.add(btnVerApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        panelprincipal.add(MostrarVentasPorMes_GUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, 850, 560));

        Admin_GUI.setMinimumSize(new java.awt.Dimension(850, 560));
        Admin_GUI.setPreferredSize(new java.awt.Dimension(850, 560));
        Admin_GUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Gestion de Apartamentos");
        Admin_GUI.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        btnVolverGestionApartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVolverGestionApartamentos.setText("Volver");
        btnVolverGestionApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverGestionApartamentosActionPerformed(evt);
            }
        });
        Admin_GUI.add(btnVolverGestionApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnAdminLimpiar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdminLimpiar1.setText("Limpiar");
        Admin_GUI.add(btnAdminLimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        tablaApartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaApartamentos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane6.setViewportView(tablaApartamentos);

        Admin_GUI.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 450, 250));

        txtAreaConstruccionGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAreaConstruccionGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaConstruccionGestionCasas1ActionPerformed(evt);
            }
        });
        Admin_GUI.add(txtAreaConstruccionGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 120, -1));

        lblAreaTerreno2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaTerreno2.setText("Area del terreno");
        Admin_GUI.add(lblAreaTerreno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        lblAreaConstruccion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaConstruccion1.setText("Area de Construccion");
        Admin_GUI.add(lblAreaConstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        lblValorFiscal2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorFiscal2.setText("Valor Fiscal");
        Admin_GUI.add(lblValorFiscal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        txtCantidadNivelesGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadNivelesGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadNivelesGestionCasas1ActionPerformed(evt);
            }
        });
        Admin_GUI.add(txtCantidadNivelesGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 120, -1));

        lblCantNiveles1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantNiveles1.setText("Altura");
        Admin_GUI.add(lblCantNiveles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        txtNumFincaGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFincaGestionCasas1ActionPerformed(evt);
            }
        });
        Admin_GUI.add(txtNumFincaGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 120, -1));

        txtAreaTerrenoGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Admin_GUI.add(txtAreaTerrenoGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 120, -1));

        txtValorMetro2GestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Admin_GUI.add(txtValorMetro2GestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 120, -1));

        txtValorFiscalGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorFiscalGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorFiscalGestionCasas1ActionPerformed(evt);
            }
        });
        Admin_GUI.add(txtValorFiscalGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 120, -1));

        lblNumFinca2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumFinca2.setText("Numero de Finca");
        Admin_GUI.add(lblNumFinca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        lblValorMetro4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorMetro4.setText("Valor por metro cuadrado");
        Admin_GUI.add(lblValorMetro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        lblEstilo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstilo1.setText("Estilo Construccion");
        Admin_GUI.add(lblEstilo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        txtAnioConstruccion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnioConstruccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioConstruccion1ActionPerformed(evt);
            }
        });
        Admin_GUI.add(txtAnioConstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 120, -1));

        lblAñoConstruccion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAñoConstruccion1.setText("Espacios Parqueo");
        Admin_GUI.add(lblAñoConstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        lblModalidad2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModalidad2.setText("Modalidad");
        Admin_GUI.add(lblModalidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        txtColor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColor1ActionPerformed(evt);
            }
        });
        Admin_GUI.add(txtColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 120, -1));

        txtEstiloConstruccionGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstiloConstruccionGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstiloConstruccionGestionCasas1ActionPerformed(evt);
            }
        });
        Admin_GUI.add(txtEstiloConstruccionGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 120, -1));

        txtModalidadGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModalidadGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModalidadGestionCasas1ActionPerformed(evt);
            }
        });
        Admin_GUI.add(txtModalidadGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 120, -1));

        lblEstilo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstilo2.setText("Piscina");
        Admin_GUI.add(lblEstilo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        btnVerCentrosComerciales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVerCentrosComerciales.setText("Ver Centros Comerciales");
        btnVerCentrosComerciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCentrosComercialesActionPerformed(evt);
            }
        });
        Admin_GUI.add(btnVerCentrosComerciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        btnSeleccionarGestionApartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSeleccionarGestionApartamentos.setText("Seleccionar");
        btnSeleccionarGestionApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarGestionApartamentosActionPerformed(evt);
            }
        });
        Admin_GUI.add(btnSeleccionarGestionApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        btnModificarGestionApartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnModificarGestionApartamentos.setText("Modificar");
        btnModificarGestionApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarGestionApartamentosActionPerformed(evt);
            }
        });
        Admin_GUI.add(btnModificarGestionApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        btnEliminarGestionApartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminarGestionApartamentos.setText("Eliminar");
        btnEliminarGestionApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGestionApartamentosActionPerformed(evt);
            }
        });
        Admin_GUI.add(btnEliminarGestionApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        panelprincipal.add(Admin_GUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 11, 850, 560));

        MostrarTop3Gerente_GUI.setMinimumSize(new java.awt.Dimension(850, 560));
        MostrarTop3Gerente_GUI.setPreferredSize(new java.awt.Dimension(850, 560));
        MostrarTop3Gerente_GUI.setRequestFocusEnabled(false);
        MostrarTop3Gerente_GUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarTop3Volver1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMostrarTop3Volver1.setText("Volver");
        btnMostrarTop3Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTop3Volver1ActionPerformed(evt);
            }
        });
        MostrarTop3Gerente_GUI.add(btnMostrarTop3Volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel24.setBackground(new java.awt.Color(0, 102, 102));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("Consultar Top 3 de clientes");
        MostrarTop3Gerente_GUI.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));
        MostrarTop3Gerente_GUI.add(txttopfechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 190, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("Desde:");
        MostrarTop3Gerente_GUI.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setText("Hasta:");
        MostrarTop3Gerente_GUI.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));
        MostrarTop3Gerente_GUI.add(txttopfechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 190, -1));

        btnMostrarTop3Consultar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMostrarTop3Consultar.setText("Consultar");
        btnMostrarTop3Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTop3ConsultarActionPerformed(evt);
            }
        });
        MostrarTop3Gerente_GUI.add(btnMostrarTop3Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        tablatop3clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablatop3clientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane5.setViewportView(tablatop3clientes);

        MostrarTop3Gerente_GUI.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 410, 180));

        panelprincipal.add(MostrarTop3Gerente_GUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, -1, -1));

        MostrarVentasPorProductoGerente_GUI.setMinimumSize(new java.awt.Dimension(850, 560));
        MostrarVentasPorProductoGerente_GUI.setPreferredSize(new java.awt.Dimension(850, 560));
        MostrarVentasPorProductoGerente_GUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarVentasPorProductoConsultar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMostrarVentasPorProductoConsultar.setText("Consultar");
        btnMostrarVentasPorProductoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVentasPorProductoConsultarActionPerformed(evt);
            }
        });
        MostrarVentasPorProductoGerente_GUI.add(btnMostrarVentasPorProductoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, 30));

        cboxMostrarProductosGerente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        MostrarVentasPorProductoGerente_GUI.add(cboxMostrarProductosGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 190, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Seleccione el producto");
        MostrarVentasPorProductoGerente_GUI.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        cbxcon2gertienda.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxcon2gertienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santa Cruz Bikes", "Rowlett Bikes" }));
        MostrarVentasPorProductoGerente_GUI.add(cbxcon2gertienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 190, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Seleccione la tienda:");
        MostrarVentasPorProductoGerente_GUI.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        txtcon2gerinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcon2gerinicioActionPerformed(evt);
            }
        });
        MostrarVentasPorProductoGerente_GUI.add(txtcon2gerinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 130, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Hasta:");
        MostrarVentasPorProductoGerente_GUI.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));
        MostrarVentasPorProductoGerente_GUI.add(txtcon2gerfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 130, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Desde:");
        MostrarVentasPorProductoGerente_GUI.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        jLabel23.setBackground(new java.awt.Color(0, 102, 102));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setText("Consultas por producto");
        MostrarVentasPorProductoGerente_GUI.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        btnMostrarVentasPorTiendaVolver1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMostrarVentasPorTiendaVolver1.setText("Volver");
        btnMostrarVentasPorTiendaVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVentasPorTiendaVolver1ActionPerformed(evt);
            }
        });
        MostrarVentasPorProductoGerente_GUI.add(btnMostrarVentasPorTiendaVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tablacon2ger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablacon2ger.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane4.setViewportView(tablacon2ger);

        MostrarVentasPorProductoGerente_GUI.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 560, 170));

        panelprincipal.add(MostrarVentasPorProductoGerente_GUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, -1, -1));

        MostrarVentasPorTiendaGerente_GUI.setMinimumSize(new java.awt.Dimension(850, 560));
        MostrarVentasPorTiendaGerente_GUI.setPreferredSize(new java.awt.Dimension(850, 560));
        MostrarVentasPorTiendaGerente_GUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarVentasPorTiendaVolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMostrarVentasPorTiendaVolver.setText("Volver");
        btnMostrarVentasPorTiendaVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVentasPorTiendaVolverActionPerformed(evt);
            }
        });
        MostrarVentasPorTiendaGerente_GUI.add(btnMostrarVentasPorTiendaVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel15.setBackground(new java.awt.Color(0, 102, 102));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Consultas por tiendas");
        MostrarVentasPorTiendaGerente_GUI.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Desde:");
        MostrarVentasPorTiendaGerente_GUI.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        MostrarVentasPorTiendaGerente_GUI.add(txtcon1gerentefin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 110, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Hasta:");
        MostrarVentasPorTiendaGerente_GUI.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));
        MostrarVentasPorTiendaGerente_GUI.add(txtcon1gerenteinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, -1));

        cboxtiendacon1gerente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboxtiendacon1gerente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santa Cruz California", "Rowlett Texas" }));
        MostrarVentasPorTiendaGerente_GUI.add(cboxtiendacon1gerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 150, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Seleccione la tienda:");
        MostrarVentasPorTiendaGerente_GUI.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        btnVentasPorTiendaConsultar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnVentasPorTiendaConsultar.setText("Consultar");
        btnVentasPorTiendaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasPorTiendaConsultarActionPerformed(evt);
            }
        });
        MostrarVentasPorTiendaGerente_GUI.add(btnVentasPorTiendaConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        tablacon1gerente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablacon1gerente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(tablacon1gerente);

        MostrarVentasPorTiendaGerente_GUI.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 720, 210));

        panelprincipal.add(MostrarVentasPorTiendaGerente_GUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, -1, -1));

        PedidoPorRangoFechas_GUI.setMinimumSize(new java.awt.Dimension(850, 560));
        PedidoPorRangoFechas_GUI.setPreferredSize(new java.awt.Dimension(850, 560));
        PedidoPorRangoFechas_GUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPedidoPorRangoFechasVolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnPedidoPorRangoFechasVolver.setText("Volver");
        btnPedidoPorRangoFechasVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoPorRangoFechasVolverActionPerformed(evt);
            }
        });
        PedidoPorRangoFechas_GUI.add(btnPedidoPorRangoFechasVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 102, 102));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Consultas por rango de fechas");
        PedidoPorRangoFechas_GUI.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Desde:");
        PedidoPorRangoFechas_GUI.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));
        PedidoPorRangoFechas_GUI.add(txtfechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 140, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Hasta:");
        PedidoPorRangoFechas_GUI.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));
        PedidoPorRangoFechas_GUI.add(txtfechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 140, -1));

        btnPedidoPorRangoFechaConsultar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnPedidoPorRangoFechaConsultar.setText("Consultar");
        btnPedidoPorRangoFechaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoPorRangoFechaConsultarActionPerformed(evt);
            }
        });
        PedidoPorRangoFechas_GUI.add(btnPedidoPorRangoFechaConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        tablaconsulta2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaconsulta2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tablaconsulta2);

        PedidoPorRangoFechas_GUI.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 660, 220));

        btnPedidoPorRangoLimpiar1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnPedidoPorRangoLimpiar1.setText("Limpiar");
        PedidoPorRangoFechas_GUI.add(btnPedidoPorRangoLimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        panelprincipal.add(PedidoPorRangoFechas_GUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, -1, -1));

        Gerente_GUI.setMinimumSize(new java.awt.Dimension(850, 560));
        Gerente_GUI.setPreferredSize(new java.awt.Dimension(850, 560));
        Gerente_GUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGerenteVolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGerenteVolver.setText("Volver");
        btnGerenteVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenteVolverActionPerformed(evt);
            }
        });
        Gerente_GUI.add(btnGerenteVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Gerente");
        Gerente_GUI.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Consultas:");
        Gerente_GUI.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        btnGerenteMostrarVentas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGerenteMostrarVentas.setText("Mostrar ventas por tienda");
        btnGerenteMostrarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenteMostrarVentasActionPerformed(evt);
            }
        });
        Gerente_GUI.add(btnGerenteMostrarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, -1));

        btnGerenteMostrarVentasPorProducto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGerenteMostrarVentasPorProducto.setText("Mostrar ventas por producto");
        btnGerenteMostrarVentasPorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenteMostrarVentasPorProductoActionPerformed(evt);
            }
        });
        Gerente_GUI.add(btnGerenteMostrarVentasPorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, -1));

        btnGerenteMostrarTop3Clientes.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGerenteMostrarTop3Clientes.setText("Mostrar el top 3 de clientes");
        btnGerenteMostrarTop3Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenteMostrarTop3ClientesActionPerformed(evt);
            }
        });
        Gerente_GUI.add(btnGerenteMostrarTop3Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, -1));

        panelprincipal.add(Gerente_GUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 1, -1, -1));

        InsertarVentaGUI.setMinimumSize(new java.awt.Dimension(850, 560));
        InsertarVentaGUI.setPreferredSize(new java.awt.Dimension(850, 560));
        InsertarVentaGUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsertarVentanaVolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnInsertarVentanaVolver.setText("Volver");
        btnInsertarVentanaVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarVentanaVolverActionPerformed(evt);
            }
        });
        InsertarVentaGUI.add(btnInsertarVentanaVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Insertar nueva venta");
        InsertarVentaGUI.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Cliente");
        InsertarVentaGUI.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cbxcliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        InsertarVentaGUI.add(cbxcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 130, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Cantidad");
        InsertarVentaGUI.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));
        InsertarVentaGUI.add(txtfechaenvioinsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 90, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Id Item");
        InsertarVentaGUI.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        cboxproducto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        InsertarVentaGUI.add(cboxproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 250, -1));

        cboxempleado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        InsertarVentaGUI.add(cboxempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 250, -1));

        btnGenerarVenta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGenerarVenta.setText("Generar venta");
        btnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaActionPerformed(evt);
            }
        });
        InsertarVentaGUI.add(btnGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 160, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setText("Seleccione empleado");
        InsertarVentaGUI.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Seleccione el producto");
        InsertarVentaGUI.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel33.setText("Fecha de envio");
        InsertarVentaGUI.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel36.setText("Fecha de la orden");
        InsertarVentaGUI.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel37.setText("Required date");
        InsertarVentaGUI.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        InsertarVentaGUI.add(txtcantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, 30));
        InsertarVentaGUI.add(txtfechaordeninsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, 30));
        InsertarVentaGUI.add(txtrequireddateinsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 90, 30));

        cbxestado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Processing", "Rejected", "Completed" }));
        InsertarVentaGUI.add(cbxestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 90, -1));
        InsertarVentaGUI.add(txtdescuentoinsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 60, 30));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel38.setText("Estado de la orden ");
        InsertarVentaGUI.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel39.setText("Precio Venta");
        InsertarVentaGUI.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        InsertarVentaGUI.add(txtprecioventainsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 60, 30));
        InsertarVentaGUI.add(txtiditeminsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 60, 30));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel40.setText("Descuento");
        InsertarVentaGUI.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        panelprincipal.add(InsertarVentaGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, -1, -1));

        getContentPane().add(panelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverGestionApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverGestionApartamentosActionPerformed
            Animacion.mover_derecha(0, 800, 5, 7, Admin_GUI);
            Animacion.mover_derecha(-800, 0, 5, 7, MostrarVentasPorMes_GUI);
            cboxempleado.removeAllItems();
    }//GEN-LAST:event_btnVolverGestionApartamentosActionPerformed

    private void btnGerenteVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenteVolverActionPerformed
        Animacion.mover_izquierda(0, -800, 5, 7, Gerente_GUI);
        Animacion.mover_izquierda(800, 0, 5, 7, Login);
    }//GEN-LAST:event_btnGerenteVolverActionPerformed

    private void btnGerenteMostrarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenteMostrarVentasActionPerformed
        Animacion.mover_derecha(0, 800, 5, 7, Gerente_GUI);
        Animacion.mover_derecha(-800, 0, 5, 7, MostrarVentasPorTiendaGerente_GUI);
    }//GEN-LAST:event_btnGerenteMostrarVentasActionPerformed

    private void btnGerenteMostrarVentasPorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenteMostrarVentasPorProductoActionPerformed
        Animacion.mover_derecha(0, 800, 5, 7, Gerente_GUI);
        Animacion.mover_derecha(-800, 0, 5, 7, MostrarVentasPorProductoGerente_GUI);
    }//GEN-LAST:event_btnGerenteMostrarVentasPorProductoActionPerformed

    private void btnGerenteMostrarTop3ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenteMostrarTop3ClientesActionPerformed
        Animacion.mover_derecha(0, 800, 5, 7, Gerente_GUI);
        Animacion.mover_derecha(-800, 0, 5, 7, MostrarTop3Gerente_GUI);     
    }//GEN-LAST:event_btnGerenteMostrarTop3ClientesActionPerformed

    private void btnInsertarVentanaVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarVentanaVolverActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 7, Admin_GUI);
        Animacion.mover_izquierda(0, -800, 5, 7, InsertarVentaGUI);  
    }//GEN-LAST:event_btnInsertarVentanaVolverActionPerformed

    private void btnPedidoPorRangoFechasVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoPorRangoFechasVolverActionPerformed
       Animacion.mover_izquierda(800, 0, 5, 7, Admin_GUI);
       Animacion.mover_izquierda(0, -800, 5, 7, PedidoPorRangoFechas_GUI);
    }//GEN-LAST:event_btnPedidoPorRangoFechasVolverActionPerformed

    private void btnMostrarVentasPorTiendaVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVentasPorTiendaVolverActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 7, Gerente_GUI);
        Animacion.mover_izquierda(0, -800, 5, 7, MostrarVentasPorTiendaGerente_GUI);
    }//GEN-LAST:event_btnMostrarVentasPorTiendaVolverActionPerformed

    private void btnMostrarVentasPorTiendaVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVentasPorTiendaVolver1ActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 7, Gerente_GUI);
        Animacion.mover_izquierda(0, -800, 5, 7, MostrarVentasPorProductoGerente_GUI);
    }//GEN-LAST:event_btnMostrarVentasPorTiendaVolver1ActionPerformed

    private void txtcon2gerinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcon2gerinicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcon2gerinicioActionPerformed
    public void resultset(String consulta, int opcion) throws SQLException {
        /*ConectarCentral obj = new ConectarCentral();
        ResultSet r;
        r = obj.Listar(consulta);
        while (r.next()) {
            switch (opcion) {
                case 1:
                    cboxproducto.addItem(r.getString(1));
                    break;                    
                case 3:
                    cbxcatcon4.addItem(r.getString(1));
                    break;
                case 4:
                    cboxempleado.addItem(r.getString(1));
                    break;
                case 5:
                    cbxcliente.addItem(r.getString(1));
                    break;
            }
      
         }
     } */
    /*public void resultset2(String consulta) throws SQLException{
        ConectarCentral obj = new ConectarCentral();
        ResultSet r;
        r = obj.Listar(consulta);
        while(r.next()){
            cboxMostrarProductosGerente.addItem(r.getString(1));           
        }
    }
          
    public void cargar_cbxcategorias(){
        cbxcatcon4.removeAll();
        String strl = "select * from cbxcategorias";
        try {
            resultset(strl, 3);
        } catch (Exception e) {
        }
    }
    public void cargar_cbxproductos_tienda(){
        String strl = "";
        if(sede.equals("Sede California")){
           strl = "select * from cbxproductosCalifornia";  
        }else{
           strl = "select * from cbxproductosTexas";
        }        
        try {
            resultset(strl,1);
        } catch (Exception e) {
        }
    }
    
    public void cargar_cbxproductoscentral(){
        String strl = "select * from cbxproductos";
        try {
            resultset2(strl);
        } catch (Exception e) {
        }
    }
    
    
    
    public void cargar_cbxempleados(){
        String strl= "";
        if(sede.equals("Sede California")){
           strl = "select * from cbxempleadosCalifornia";  
        }else{
           strl = "select * from cbxempleadosTexas";
        }
        try {
            resultset(strl, 4);
        } catch (Exception e) {
        }                
    }
    
    public void cargar_cbxclientes(){      
        String strl = "";
        if(sede.equals("Sede California")){
            strl = "select * from cbxclientesCalifornia";
        }else{
            strl = "select * from cbxclientesTexas";
        }
        try {
            resultset(strl, 5);
        } catch (Exception e) {
        }   
    }
    
    public int obtener_id_producto(String producto_seleccionado) throws SQLException{
        int idproducto=0;
        String producto_vista;
        ResultSet r;
        String consulta = "SELECT * FROM vistaproductos";
        ConectarCentral obj = new ConectarCentral();
        r = obj.Listar(consulta);
        while (r.next()) {
            idproducto = Integer.parseInt(r.getString(1));
            producto_vista = r.getString(2);
            if (producto_vista.equals(producto_seleccionado)) {
                return idproducto;
            }
        }
        return idproducto;            
    }
       
    public int obtener_id_cliente(String cliente_seleccionado,String sede) throws SQLException{
        int idcliente = 0;
        String cliente_vista;
        ResultSet r;
        String consulta = "";
        if(sede.equals("Sede California")){
            consulta = "SELECT * FROM vistaclientescalifornia";          
        }else{
            consulta = "SELECT * FROM vistaclientestexas"; 
        }
        ConectarCentral obj = new ConectarCentral();
        r = obj.Listar(consulta);
        while(r.next()){
            idcliente = Integer.parseInt(r.getString(1));
            cliente_vista = r.getString(2);
            if(cliente_vista.equals(cliente_seleccionado)){
                return idcliente;               
            }                    
        }
        return idcliente;
    }
    
    public int obtener_id_empleado(String empleado_seleccionado) throws SQLException{
        int idempleado = 0;
        String empleado_vista;
        ResultSet r;
        String consulta = "select * from vistaempleados";
        ConectarCentral obj = new ConectarCentral();
        r = obj.Listar(consulta);
        while(r.next()){
            idempleado = Integer.parseInt(r.getString(1));
            empleado_vista = r.getString(2);
            if(empleado_vista.equals(empleado_seleccionado)){
                return idempleado;
            }
        }
        return idempleado;
    }*/
    
    
//    public void limpiar_tablaconsulta2(){
       tablaconsulta2.removeAll();
    }
    
    public void limpiar_tablaadmin(){
        tablaApartamentos.removeAll();
    }

    private void btnPedidoPorRangoFechaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoPorRangoFechaConsultarActionPerformed
      /* limpiar_tablaconsulta2();
       if(txtfechainicio.getText().equals("") || txtfechafin.getText().equals("")){
           JOptionPane.showMessageDialog(null, "EL CAMPO NO PUEDE ESTAR VACIO");
       }else{                
           consulta2 tabla_consulta2 = new consulta2();
           tabla_consulta2.visualizar_consulta2(tablaconsulta2,txtfechainicio.getText(),txtfechafin.getText(),sede);       
       }  */      
    }//GEN-LAST:event_btnPedidoPorRangoFechaConsultarActionPerformed

    private void btnMostrarTop3Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTop3Volver1ActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 7, Gerente_GUI);
        Animacion.mover_izquierda(0, -800, 5, 7, MostrarTop3Gerente_GUI);   
    }//GEN-LAST:event_btnMostrarTop3Volver1ActionPerformed

    private void btnVolverGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverGestionCasasActionPerformed
        Animacion.mover_derecha(0, 800, 5, 7, MostrarVentasPorMes_GUI);
        Animacion.mover_derecha(-800, 0, 5, 7, Login);
    }//GEN-LAST:event_btnVolverGestionCasasActionPerformed

    private void btnMostrarTop3ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTop3ConsultarActionPerformed
       /*if(txttopfechainicio.getText().equals("") || txttopfechafin.getText().equals("")){
           JOptionPane.showMessageDialog(null, "EL CAMPO NO PUEDE ESTAR VACIO");
       }else{                
           consulta3_gerente tabla_consulta3_gerente = new consulta3_gerente();
           tabla_consulta3_gerente.visualizar_consulta3_gerente(tablatop3clientes,txtfechainicio.getText(),txtfechafin.getText());       
       } */
    }//GEN-LAST:event_btnMostrarTop3ConsultarActionPerformed

    private void btnVentasPorTiendaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasPorTiendaConsultarActionPerformed
       /* int idTienda=0;
        if(txtcon1gerenteinicio.getText().equals("") || txtcon1gerentefin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "EL CAMPO NO PUEDE ESTAR VACIO");
        }else{
            if(cboxtiendacon1gerente.getSelectedItem().equals("Santa Cruz California")){
                idTienda = 1;
            }else{
                idTienda = 3;
            }
            consulta1_gerente tabla_consulta1_gerente = new consulta1_gerente();
            tabla_consulta1_gerente.visualizar_consulta1(tablacon1gerente, txtcon1gerenteinicio.getText(), txtcon1gerentefin.getText(), idTienda);
        }*/
        
    }//GEN-LAST:event_btnVentasPorTiendaConsultarActionPerformed

    private void btnMostrarVentasPorProductoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVentasPorProductoConsultarActionPerformed
       /* if(txtcon2gerinicio.getText().equals("") || txtcon2gerfin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "EL CAMPO NO PUEDE ESTAR VACIO");
        }else{
            consulta2_gerente tabla_consulta2_gerente = new consulta2_gerente();
            tabla_consulta2_gerente.visualizar_consulta2(tablacon2ger, txtcon2gerinicio.getText(), txtcon2gerfin.getText(), cbxcon2gertienda.getSelectedItem().toString(),cboxMostrarProductosGerente.getSelectedItem().toString());
        }  */     
    }//GEN-LAST:event_btnMostrarVentasPorProductoConsultarActionPerformed

    private void btnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaActionPerformed
        /*try {  
            int idProducto = obtener_id_producto(cboxproducto.getSelectedItem().toString());
            int idCliente = obtener_id_cliente(cbxcliente.getSelectedItem().toString(),sede);
            int idEmpleado = obtener_id_empleado(cboxempleado.getSelectedItem().toString());
            int cantidad = Integer.parseInt(txtcantidad1.getText());
            String fechaOrden = txtfechaordeninsertar.getText().toString();
            String fechaEnvio = txtfechaenvioinsertar.getText().toString();
            String requiredDate = txtrequireddateinsertar.getText().toString();
            String estadoOrden = cbxestado.getSelectedItem().toString();
            float precioVenta = Float.parseFloat(txtprecioventainsertar.getText());
            float descuento = Float.parseFloat(txtdescuentoinsertar.getText());
            int idItem = Integer.parseInt(txtiditeminsertar.getText());
            int estadoOrdenId = 0;
            if(estadoOrden.equals("Pending")){ estadoOrdenId = 1;}
            if(estadoOrden.equals("Processing")){estadoOrdenId = 2;}
            if(estadoOrden.equals("Rejected")){estadoOrdenId = 3;}
            if(estadoOrden.equals("Completed")){estadoOrdenId= 4;}
            int idTienda = 0;
            if(sede.equals("Sede California")){idTienda = 1; }
            if(sede.equals("Sede Texas")){idTienda = 3 ;} 
                        
            InsercionTienda insertTienda = new InsercionTienda();
            //InsercionCentral insertCentral = new InsercionCentral();
              
            if(insertTienda.insertarOrden(idCliente, estadoOrdenId, fechaOrden,requiredDate,fechaEnvio,idTienda,idEmpleado,sede)==true){
                insertTienda.insertarDetalleOrden(idItem,idProducto,cantidad,precioVenta,descuento,sede);                
            }
            else{
                JOptionPane.showMessageDialog(null, "NO SE PUDO REALIZAR LA INSERCION");
            }           
            //insertCentral.insertarOrden(idCliente, estadoOrdenId, fechaOrden, requiredDate, fechaEnvio, idTienda, idEmpleado);
            //insertCentral.insertarDetalleOrden(idItem, idProducto, cantidad, precioVenta, descuento);
            
        } catch (SQLException ex) {
            Logger.getLogger(GestionCatalogoFrame.class.getName()).log(Level.SEVERE, null, ex);
        } */
    }//GEN-LAST:event_btnGenerarVentaActionPerformed

    private void txtValorFiscalGestionLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFiscalGestionLotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFiscalGestionLotesActionPerformed

    private void txtModalidadGestionLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModalidadGestionLotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModalidadGestionLotesActionPerformed

    private void btnVerCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCasasActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 10, MostrarVentasPorMes_GUI);
        Animacion.mover_izquierda(0, -800, 5, 10, Login );
    }//GEN-LAST:event_btnVerCasasActionPerformed

    private void txtAreaConstruccionGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaConstruccionGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaConstruccionGestionCasasActionPerformed

    private void txtCantidadNivelesGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadNivelesGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadNivelesGestionCasasActionPerformed

    private void txtNumFincaGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFincaGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFincaGestionCasasActionPerformed

    private void txtValorFiscalGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFiscalGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFiscalGestionCasasActionPerformed

    private void txtAnioConstruccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioConstruccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioConstruccionActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtEstiloConstruccionGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstiloConstruccionGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstiloConstruccionGestionCasasActionPerformed

    private void txtModalidadGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModalidadGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModalidadGestionCasasActionPerformed

    private void btnVerApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerApartamentosActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 10, Admin_GUI);
        Animacion.mover_izquierda(0, -800, 5, 10, MostrarVentasPorMes_GUI );
    }//GEN-LAST:event_btnVerApartamentosActionPerformed

    private void btnVolverGestionLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverGestionLotesActionPerformed
        MenuAgentesFrame ventana = new MenuAgentesFrame();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverGestionLotesActionPerformed

    private void txtAreaConstruccionGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaConstruccionGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaConstruccionGestionCasas1ActionPerformed

    private void txtCantidadNivelesGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadNivelesGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadNivelesGestionCasas1ActionPerformed

    private void txtNumFincaGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFincaGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFincaGestionCasas1ActionPerformed

    private void txtValorFiscalGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFiscalGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFiscalGestionCasas1ActionPerformed

    private void txtAnioConstruccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioConstruccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioConstruccion1ActionPerformed

    private void txtColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColor1ActionPerformed

    private void txtEstiloConstruccionGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstiloConstruccionGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstiloConstruccionGestionCasas1ActionPerformed

    private void txtModalidadGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModalidadGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModalidadGestionCasas1ActionPerformed

    private void btnVerCentrosComercialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCentrosComercialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerCentrosComercialesActionPerformed

    private void btnSeleccionarGestionApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarGestionApartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarGestionApartamentosActionPerformed

    private void btnModificarGestionApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarGestionApartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarGestionApartamentosActionPerformed

    private void btnEliminarGestionApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGestionApartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarGestionApartamentosActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCatalogoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin_GUI;
    private javax.swing.JPanel Gerente_GUI;
    private javax.swing.JPanel InsertarVentaGUI;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel MostrarTop3Gerente_GUI;
    private javax.swing.JPanel MostrarVentasPorMes_GUI;
    private javax.swing.JPanel MostrarVentasPorProductoGerente_GUI;
    private javax.swing.JPanel MostrarVentasPorTiendaGerente_GUI;
    private javax.swing.JPanel PedidoPorRangoFechas_GUI;
    public javax.swing.JToggleButton btnAdminLimpiar1;
    public javax.swing.JToggleButton btnEliminarGestionApartamentos;
    public javax.swing.JToggleButton btnEliminarGestionCasas;
    private javax.swing.JButton btnEliminarGestionLotes;
    public javax.swing.JToggleButton btnGenerarVenta;
    public javax.swing.JToggleButton btnGerenteMostrarTop3Clientes;
    public javax.swing.JToggleButton btnGerenteMostrarVentas;
    public javax.swing.JToggleButton btnGerenteMostrarVentasPorProducto;
    public javax.swing.JToggleButton btnGerenteVolver;
    public javax.swing.JToggleButton btnInsertarVentanaVolver;
    public javax.swing.JToggleButton btnLimpiarGestionCasas;
    public javax.swing.JToggleButton btnModificarGestionApartamentos;
    public javax.swing.JToggleButton btnModificarGestionCasas;
    private javax.swing.JButton btnModificarGestionLotes;
    public javax.swing.JToggleButton btnMostrarTop3Consultar;
    public javax.swing.JToggleButton btnMostrarTop3Volver1;
    public javax.swing.JToggleButton btnMostrarVentasPorProductoConsultar;
    public javax.swing.JToggleButton btnMostrarVentasPorTiendaVolver;
    public javax.swing.JToggleButton btnMostrarVentasPorTiendaVolver1;
    public javax.swing.JToggleButton btnPedidoPorRangoFechaConsultar;
    public javax.swing.JToggleButton btnPedidoPorRangoFechasVolver;
    public javax.swing.JToggleButton btnPedidoPorRangoLimpiar1;
    public javax.swing.JToggleButton btnSeleccionarGestionApartamentos;
    public javax.swing.JToggleButton btnSeleccionarGestionCasas;
    private javax.swing.JButton btnSeleccionarGestionLotes;
    public javax.swing.JToggleButton btnVentasPorTiendaConsultar;
    public javax.swing.JToggleButton btnVerApartamentos;
    private javax.swing.JButton btnVerCasas;
    public javax.swing.JToggleButton btnVerCentrosComerciales;
    public javax.swing.JToggleButton btnVolverGestionApartamentos;
    public javax.swing.JToggleButton btnVolverGestionCasas;
    private javax.swing.JButton btnVolverGestionLotes;
    public javax.swing.JComboBox<String> cboxMostrarProductosGerente;
    public javax.swing.JComboBox<String> cboxempleado;
    public javax.swing.JComboBox<String> cboxproducto;
    public javax.swing.JComboBox<String> cboxtiendacon1gerente;
    public javax.swing.JComboBox<String> cbxcliente;
    public javax.swing.JComboBox<String> cbxcon2gertienda;
    public javax.swing.JComboBox<String> cbxestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblAreaConstruccion;
    private javax.swing.JLabel lblAreaConstruccion1;
    private javax.swing.JLabel lblAreaTerreno;
    private javax.swing.JLabel lblAreaTerreno1;
    private javax.swing.JLabel lblAreaTerreno2;
    private javax.swing.JLabel lblAñoConstruccion;
    private javax.swing.JLabel lblAñoConstruccion1;
    private javax.swing.JLabel lblCantNiveles;
    private javax.swing.JLabel lblCantNiveles1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblEstilo1;
    private javax.swing.JLabel lblEstilo2;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblModalidad1;
    private javax.swing.JLabel lblModalidad2;
    private javax.swing.JLabel lblNumFinca;
    private javax.swing.JLabel lblNumFinca1;
    private javax.swing.JLabel lblNumFinca2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblValorFiscal;
    private javax.swing.JLabel lblValorFiscal1;
    private javax.swing.JLabel lblValorFiscal2;
    private javax.swing.JLabel lblValorMetro2;
    private javax.swing.JLabel lblValorMetro3;
    private javax.swing.JLabel lblValorMetro4;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JTable tablaApartamentos;
    private javax.swing.JTable tablaCasas;
    private javax.swing.JTable tablaLotes;
    private javax.swing.JTable tablacon1gerente;
    private javax.swing.JTable tablacon2ger;
    private javax.swing.JTable tablaconsulta2;
    private javax.swing.JTable tablatop3clientes;
    private javax.swing.JTextField txtAnioConstruccion;
    private javax.swing.JTextField txtAnioConstruccion1;
    private javax.swing.JTextField txtAreaConstruccionGestionCasas;
    private javax.swing.JTextField txtAreaConstruccionGestionCasas1;
    private javax.swing.JTextField txtAreaTerrenoGestionCasas;
    private javax.swing.JTextField txtAreaTerrenoGestionCasas1;
    private javax.swing.JTextField txtAreaTerrenoGestionLotes;
    private javax.swing.JTextField txtCantidadNivelesGestionCasas;
    private javax.swing.JTextField txtCantidadNivelesGestionCasas1;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtColor1;
    private javax.swing.JTextField txtEstiloConstruccionGestionCasas;
    private javax.swing.JTextField txtEstiloConstruccionGestionCasas1;
    private javax.swing.JTextField txtModalidadGestionCasas;
    private javax.swing.JTextField txtModalidadGestionCasas1;
    private javax.swing.JTextField txtModalidadGestionLotes;
    private javax.swing.JTextField txtNumFincaGestionCasas;
    private javax.swing.JTextField txtNumFincaGestionCasas1;
    private javax.swing.JTextField txtNumFincaGestionLotes;
    private javax.swing.JTextField txtValorFiscalGestionCasas;
    private javax.swing.JTextField txtValorFiscalGestionCasas1;
    private javax.swing.JTextField txtValorFiscalGestionLotes;
    private javax.swing.JTextField txtValorMetro2GestionCasas;
    private javax.swing.JTextField txtValorMetro2GestionCasas1;
    private javax.swing.JTextField txtValorMetro2GestionLotes;
    public javax.swing.JTextField txtcantidad1;
    public javax.swing.JTextField txtcon1gerentefin;
    public javax.swing.JTextField txtcon1gerenteinicio;
    public javax.swing.JTextField txtcon2gerfin;
    public javax.swing.JTextField txtcon2gerinicio;
    private javax.swing.JTextField txtdescuentoinsertar;
    public javax.swing.JTextField txtfechaenvioinsertar;
    public javax.swing.JTextField txtfechafin;
    public javax.swing.JTextField txtfechainicio;
    public javax.swing.JTextField txtfechaordeninsertar;
    private javax.swing.JTextField txtiditeminsertar;
    private javax.swing.JTextField txtprecioventainsertar;
    public javax.swing.JTextField txtrequireddateinsertar;
    public javax.swing.JTextField txttopfechafin;
    public javax.swing.JTextField txttopfechainicio;
    // End of variables declaration//GEN-END:variables
}
