
package Vista;

import Animacion.Animacion;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GestionCatalogoFrame extends javax.swing.JFrame {

    public GestionCatalogoFrame() {
        initComponents();                       
        //cargar_cbxcategorias();
        //cargar_cbxproductoscentral();
    }
    public String sede;
    public String tipo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprincipal = new javax.swing.JPanel();
        GestionLotes = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaLotes = new javax.swing.JTable();
        lblModalidad = new javax.swing.JLabel();
        lblNumFinca = new javax.swing.JLabel();
        lblAreaTerreno = new javax.swing.JLabel();
        lblValorFiscal = new javax.swing.JLabel();
        txtNumFincaGestionLotes = new javax.swing.JTextField();
        txtAreaTerrenoGestionLotes = new javax.swing.JTextField();
        txtValorFiscalGestionLotes = new javax.swing.JTextField();
        txtModalidadGestionLotes = new javax.swing.JTextField();
        lblValorMetro2 = new javax.swing.JLabel();
        txtValorMetro2GestionLotes = new javax.swing.JTextField();
        btnModificarGestionLotes = new javax.swing.JButton();
        btnSeleccionarGestionLotes = new javax.swing.JButton();
        btnVerCasas = new javax.swing.JButton();
        btnVolverGestionLotes = new javax.swing.JButton();
        btnEliminarGestionLotes = new javax.swing.JButton();
        GestionCasas = new javax.swing.JPanel();
        btnVolverGestionCasas = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCasas = new javax.swing.JTable();
        btnLimpiarGestionCasas = new javax.swing.JToggleButton();
        lblTitulo1 = new javax.swing.JLabel();
        txtAreaConstruccionGestionCasas = new javax.swing.JTextField();
        lblAreaTerreno1 = new javax.swing.JLabel();
        lblAreaConstruccion = new javax.swing.JLabel();
        lblValorFiscal1 = new javax.swing.JLabel();
        txtCantidadNivelesGestionCasas = new javax.swing.JTextField();
        lblCantNiveles = new javax.swing.JLabel();
        txtNumFincaGestionCasas = new javax.swing.JTextField();
        txtAreaTerrenoGestionCasas = new javax.swing.JTextField();
        txtValorMetro2GestionCasas = new javax.swing.JTextField();
        txtValorFiscalGestionCasas = new javax.swing.JTextField();
        lblNumFinca1 = new javax.swing.JLabel();
        lblValorMetro3 = new javax.swing.JLabel();
        lblEstilo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        txtAnioConstruccion = new javax.swing.JTextField();
        lblAñoConstruccion = new javax.swing.JLabel();
        lblModalidad1 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        txtEstiloConstruccionGestionCasas = new javax.swing.JTextField();
        txtModalidadGestionCasas = new javax.swing.JTextField();
        btnSeleccionarGestionCasas = new javax.swing.JToggleButton();
        btnModificarGestionCasas = new javax.swing.JToggleButton();
        btnEliminarGestionCasas = new javax.swing.JToggleButton();
        btnVerApartamentos = new javax.swing.JToggleButton();
        GestionApartamentos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolverGestionApartamentos = new javax.swing.JToggleButton();
        btnAdminLimpiar1 = new javax.swing.JToggleButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaApartamentos = new javax.swing.JTable();
        txtAreaConstruccionGestionCasas1 = new javax.swing.JTextField();
        lblAreaTerreno2 = new javax.swing.JLabel();
        lblAreaConstruccion1 = new javax.swing.JLabel();
        lblValorFiscal2 = new javax.swing.JLabel();
        txtCantidadNivelesGestionCasas1 = new javax.swing.JTextField();
        lblCantNiveles1 = new javax.swing.JLabel();
        txtNumFincaGestionCasas1 = new javax.swing.JTextField();
        txtAreaTerrenoGestionCasas1 = new javax.swing.JTextField();
        txtValorMetro2GestionCasas1 = new javax.swing.JTextField();
        txtValorFiscalGestionCasas1 = new javax.swing.JTextField();
        lblNumFinca2 = new javax.swing.JLabel();
        lblValorMetro4 = new javax.swing.JLabel();
        lblEstilo1 = new javax.swing.JLabel();
        txtAnioConstruccion1 = new javax.swing.JTextField();
        lblAñoConstruccion1 = new javax.swing.JLabel();
        lblModalidad2 = new javax.swing.JLabel();
        txtColor1 = new javax.swing.JTextField();
        txtEstiloConstruccionGestionCasas1 = new javax.swing.JTextField();
        txtModalidadGestionCasas1 = new javax.swing.JTextField();
        lblEstilo2 = new javax.swing.JLabel();
        btnVerCentrosComerciales = new javax.swing.JToggleButton();
        btnSeleccionarGestionApartamentos = new javax.swing.JToggleButton();
        btnModificarGestionApartamentos = new javax.swing.JToggleButton();
        btnEliminarGestionApartamentos = new javax.swing.JToggleButton();
        GestionCentrosComerciales = new javax.swing.JPanel();
        btnVolverGestionCentrosComerciales = new javax.swing.JToggleButton();
        lblTituloCentrosC = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaCentrosComerciales = new javax.swing.JTable();
        txtAreaConstruccionGestionCC = new javax.swing.JTextField();
        lblAreaTerreno3 = new javax.swing.JLabel();
        lblAreaConstruccion2 = new javax.swing.JLabel();
        lblValorFiscal3 = new javax.swing.JLabel();
        txtCantidadTiendas = new javax.swing.JTextField();
        txtNumFincaGestionCC = new javax.swing.JTextField();
        txtAreaTerrenoGestionCC = new javax.swing.JTextField();
        txtValorMetro2GestionCC = new javax.swing.JTextField();
        txtValorFiscalGestionCC = new javax.swing.JTextField();
        lblNumFincaGestionCC = new javax.swing.JLabel();
        lblCantTiendas = new javax.swing.JLabel();
        lblEstilo3 = new javax.swing.JLabel();
        txtEspaciosGestionCC = new javax.swing.JTextField();
        lblEspacios = new javax.swing.JLabel();
        lblModalidad3 = new javax.swing.JLabel();
        txtCantidadSalasCines = new javax.swing.JTextField();
        txtEstiloConstruccionGestionCC = new javax.swing.JTextField();
        txtModalidadGestionCC = new javax.swing.JTextField();
        lblValorMetro6 = new javax.swing.JLabel();
        lblCantTiendas1 = new javax.swing.JLabel();
        lblCantTiendas2 = new javax.swing.JLabel();
        txtCadenaCine = new javax.swing.JTextField();
        lblCantHotspot = new javax.swing.JLabel();
        txtCantidadEscaleras = new javax.swing.JTextField();
        lblCantEscaleras = new javax.swing.JLabel();
        txtCantidadHotspot = new javax.swing.JTextField();
        btnRegresarGestionCC = new javax.swing.JToggleButton();
        btnSeleccionarGestionCC = new javax.swing.JToggleButton();
        btnModificarGestionCC = new javax.swing.JToggleButton();
        btnEliminarGestionCC = new javax.swing.JToggleButton();
        MostrarVentasPorProductoGerente_GUI = new javax.swing.JPanel();
        btnMostrarVentasPorProductoConsultar = new javax.swing.JToggleButton();
        cboxMostrarProductosGerente = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbxcon2gertienda = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtcon2gerinicio = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtcon2gerfin = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnMostrarVentasPorTiendaVolver1 = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablacon2ger = new javax.swing.JTable();
        MostrarVentasPorTiendaGerente_GUI = new javax.swing.JPanel();
        btnMostrarVentasPorTiendaVolver = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtcon1gerentefin = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtcon1gerenteinicio = new javax.swing.JTextField();
        cboxtiendacon1gerente = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        btnVentasPorTiendaConsultar = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablacon1gerente = new javax.swing.JTable();
        PedidoPorRangoFechas_GUI = new javax.swing.JPanel();
        btnPedidoPorRangoFechasVolver = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtfechainicio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtfechafin = new javax.swing.JTextField();
        btnPedidoPorRangoFechaConsultar = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaconsulta2 = new javax.swing.JTable();
        btnPedidoPorRangoLimpiar1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprincipal.setMinimumSize(new java.awt.Dimension(850, 560));
        panelprincipal.setName(""); // NOI18N
        panelprincipal.setPreferredSize(new java.awt.Dimension(850, 560));
        panelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GestionLotes.setPreferredSize(new java.awt.Dimension(850, 560));
        GestionLotes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestion de Lotes");
        GestionLotes.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 200, 40));

        tablaLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(tablaLotes);

        GestionLotes.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 480, 220));

        lblModalidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModalidad.setText("Modalidad");
        GestionLotes.add(lblModalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        lblNumFinca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumFinca.setText("Numero de Finca");
        GestionLotes.add(lblNumFinca, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        lblAreaTerreno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaTerreno.setText("Area del terreno");
        GestionLotes.add(lblAreaTerreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        lblValorFiscal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorFiscal.setText("Valor Fiscal");
        GestionLotes.add(lblValorFiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));
        GestionLotes.add(txtNumFincaGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 130, 30));

        txtAreaTerrenoGestionLotes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GestionLotes.add(txtAreaTerrenoGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 130, 30));

        txtValorFiscalGestionLotes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorFiscalGestionLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorFiscalGestionLotesActionPerformed(evt);
            }
        });
        GestionLotes.add(txtValorFiscalGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 130, 30));

        txtModalidadGestionLotes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModalidadGestionLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModalidadGestionLotesActionPerformed(evt);
            }
        });
        GestionLotes.add(txtModalidadGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 130, 30));

        lblValorMetro2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorMetro2.setText("Valor por metro cuadrado");
        GestionLotes.add(lblValorMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        txtValorMetro2GestionLotes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GestionLotes.add(txtValorMetro2GestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 60, 30));

        btnModificarGestionLotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificarGestionLotes.setText("Modificar");
        GestionLotes.add(btnModificarGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, 30));

        btnSeleccionarGestionLotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSeleccionarGestionLotes.setText("Seleccionar");
        GestionLotes.add(btnSeleccionarGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, 30));

        btnVerCasas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVerCasas.setText("Ver Casas");
        btnVerCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCasasActionPerformed(evt);
            }
        });
        GestionLotes.add(btnVerCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 100, 30));

        btnVolverGestionLotes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVolverGestionLotes.setText("Volver");
        btnVolverGestionLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverGestionLotesActionPerformed(evt);
            }
        });
        GestionLotes.add(btnVolverGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 80, 20));

        btnEliminarGestionLotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarGestionLotes.setText("Eliminar");
        GestionLotes.add(btnEliminarGestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 100, 30));

        panelprincipal.add(GestionLotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 810, 560));
        GestionLotes.getAccessibleContext().setAccessibleName("");

        GestionCasas.setMinimumSize(new java.awt.Dimension(850, 560));
        GestionCasas.setPreferredSize(new java.awt.Dimension(850, 560));
        GestionCasas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverGestionCasas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVolverGestionCasas.setText("Volver");
        btnVolverGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverGestionCasasActionPerformed(evt);
            }
        });
        GestionCasas.add(btnVolverGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        tablaCasas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCasas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tablaCasas);

        GestionCasas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 440, 270));

        btnLimpiarGestionCasas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpiarGestionCasas.setText("Limpiar");
        GestionCasas.add(btnLimpiarGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        lblTitulo1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Gestion de Casas");
        GestionCasas.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 200, 40));

        txtAreaConstruccionGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAreaConstruccionGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaConstruccionGestionCasasActionPerformed(evt);
            }
        });
        GestionCasas.add(txtAreaConstruccionGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 120, -1));

        lblAreaTerreno1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaTerreno1.setText("Area del terreno");
        GestionCasas.add(lblAreaTerreno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        lblAreaConstruccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaConstruccion.setText("Area de Construccion");
        GestionCasas.add(lblAreaConstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        lblValorFiscal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorFiscal1.setText("Valor Fiscal");
        GestionCasas.add(lblValorFiscal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        txtCantidadNivelesGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadNivelesGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadNivelesGestionCasasActionPerformed(evt);
            }
        });
        GestionCasas.add(txtCantidadNivelesGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 120, -1));

        lblCantNiveles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantNiveles.setText("Cantidad de Niveles");
        GestionCasas.add(lblCantNiveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        txtNumFincaGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFincaGestionCasasActionPerformed(evt);
            }
        });
        GestionCasas.add(txtNumFincaGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 120, -1));

        txtAreaTerrenoGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GestionCasas.add(txtAreaTerrenoGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 120, -1));

        txtValorMetro2GestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GestionCasas.add(txtValorMetro2GestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 120, -1));

        txtValorFiscalGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorFiscalGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorFiscalGestionCasasActionPerformed(evt);
            }
        });
        GestionCasas.add(txtValorFiscalGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 120, -1));

        lblNumFinca1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumFinca1.setText("Numero de Finca");
        GestionCasas.add(lblNumFinca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        lblValorMetro3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorMetro3.setText("Valor por metro cuadrado");
        GestionCasas.add(lblValorMetro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        lblEstilo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstilo.setText("Estilo Construccion");
        GestionCasas.add(lblEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        lblColor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblColor.setText("Color");
        GestionCasas.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        txtAnioConstruccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnioConstruccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioConstruccionActionPerformed(evt);
            }
        });
        GestionCasas.add(txtAnioConstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 120, -1));

        lblAñoConstruccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAñoConstruccion.setText("Año de Construcción");
        GestionCasas.add(lblAñoConstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        lblModalidad1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModalidad1.setText("Modalidad");
        GestionCasas.add(lblModalidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        txtColor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        GestionCasas.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 120, -1));

        txtEstiloConstruccionGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstiloConstruccionGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstiloConstruccionGestionCasasActionPerformed(evt);
            }
        });
        GestionCasas.add(txtEstiloConstruccionGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 120, -1));

        txtModalidadGestionCasas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModalidadGestionCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModalidadGestionCasasActionPerformed(evt);
            }
        });
        GestionCasas.add(txtModalidadGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 120, -1));

        btnSeleccionarGestionCasas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSeleccionarGestionCasas.setText("Seleccionar");
        GestionCasas.add(btnSeleccionarGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        btnModificarGestionCasas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnModificarGestionCasas.setText("Modificar");
        GestionCasas.add(btnModificarGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        btnEliminarGestionCasas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminarGestionCasas.setText("Eliminar");
        GestionCasas.add(btnEliminarGestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        btnVerApartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVerApartamentos.setText("Ver Apartamentos");
        btnVerApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerApartamentosActionPerformed(evt);
            }
        });
        GestionCasas.add(btnVerApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        panelprincipal.add(GestionCasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, 850, 560));

        GestionApartamentos.setMinimumSize(new java.awt.Dimension(850, 560));
        GestionApartamentos.setPreferredSize(new java.awt.Dimension(850, 560));
        GestionApartamentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Gestion de Apartamentos");
        GestionApartamentos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        btnVolverGestionApartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVolverGestionApartamentos.setText("Volver");
        btnVolverGestionApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverGestionApartamentosActionPerformed(evt);
            }
        });
        GestionApartamentos.add(btnVolverGestionApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnAdminLimpiar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdminLimpiar1.setText("Limpiar");
        GestionApartamentos.add(btnAdminLimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        tablaApartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaApartamentos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane6.setViewportView(tablaApartamentos);

        GestionApartamentos.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 470, 270));

        txtAreaConstruccionGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAreaConstruccionGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaConstruccionGestionCasas1ActionPerformed(evt);
            }
        });
        GestionApartamentos.add(txtAreaConstruccionGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 120, -1));

        lblAreaTerreno2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAreaTerreno2.setText("Area del terreno");
        GestionApartamentos.add(lblAreaTerreno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        lblAreaConstruccion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAreaConstruccion1.setText("Area de Construccion");
        GestionApartamentos.add(lblAreaConstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        lblValorFiscal2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValorFiscal2.setText("Valor Fiscal");
        GestionApartamentos.add(lblValorFiscal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        txtCantidadNivelesGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadNivelesGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadNivelesGestionCasas1ActionPerformed(evt);
            }
        });
        GestionApartamentos.add(txtCantidadNivelesGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 120, -1));

        lblCantNiveles1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCantNiveles1.setText("Altura");
        GestionApartamentos.add(lblCantNiveles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        txtNumFincaGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFincaGestionCasas1ActionPerformed(evt);
            }
        });
        GestionApartamentos.add(txtNumFincaGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 120, -1));

        txtAreaTerrenoGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GestionApartamentos.add(txtAreaTerrenoGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 120, -1));

        txtValorMetro2GestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GestionApartamentos.add(txtValorMetro2GestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 120, -1));

        txtValorFiscalGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorFiscalGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorFiscalGestionCasas1ActionPerformed(evt);
            }
        });
        GestionApartamentos.add(txtValorFiscalGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 120, -1));

        lblNumFinca2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumFinca2.setText("Numero de Finca");
        GestionApartamentos.add(lblNumFinca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        lblValorMetro4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValorMetro4.setText("Valor por metro cuadrado");
        GestionApartamentos.add(lblValorMetro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        lblEstilo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstilo1.setText("Estilo Construccion");
        GestionApartamentos.add(lblEstilo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        txtAnioConstruccion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnioConstruccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioConstruccion1ActionPerformed(evt);
            }
        });
        GestionApartamentos.add(txtAnioConstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 120, -1));

        lblAñoConstruccion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAñoConstruccion1.setText("Espacios Parqueo");
        GestionApartamentos.add(lblAñoConstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        lblModalidad2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModalidad2.setText("Modalidad");
        GestionApartamentos.add(lblModalidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        txtColor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColor1ActionPerformed(evt);
            }
        });
        GestionApartamentos.add(txtColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 120, -1));

        txtEstiloConstruccionGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstiloConstruccionGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstiloConstruccionGestionCasas1ActionPerformed(evt);
            }
        });
        GestionApartamentos.add(txtEstiloConstruccionGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 120, -1));

        txtModalidadGestionCasas1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModalidadGestionCasas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModalidadGestionCasas1ActionPerformed(evt);
            }
        });
        GestionApartamentos.add(txtModalidadGestionCasas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 120, -1));

        lblEstilo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstilo2.setText("Piscina");
        GestionApartamentos.add(lblEstilo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        btnVerCentrosComerciales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVerCentrosComerciales.setText("Ver Centros Comerciales");
        btnVerCentrosComerciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCentrosComercialesActionPerformed(evt);
            }
        });
        GestionApartamentos.add(btnVerCentrosComerciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        btnSeleccionarGestionApartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSeleccionarGestionApartamentos.setText("Seleccionar");
        btnSeleccionarGestionApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarGestionApartamentosActionPerformed(evt);
            }
        });
        GestionApartamentos.add(btnSeleccionarGestionApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        btnModificarGestionApartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnModificarGestionApartamentos.setText("Modificar");
        btnModificarGestionApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarGestionApartamentosActionPerformed(evt);
            }
        });
        GestionApartamentos.add(btnModificarGestionApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        btnEliminarGestionApartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminarGestionApartamentos.setText("Eliminar");
        btnEliminarGestionApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGestionApartamentosActionPerformed(evt);
            }
        });
        GestionApartamentos.add(btnEliminarGestionApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        panelprincipal.add(GestionApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 11, 850, 560));

        GestionCentrosComerciales.setMinimumSize(new java.awt.Dimension(850, 560));
        GestionCentrosComerciales.setPreferredSize(new java.awt.Dimension(850, 560));
        GestionCentrosComerciales.setRequestFocusEnabled(false);
        GestionCentrosComerciales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverGestionCentrosComerciales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVolverGestionCentrosComerciales.setText("Volver");
        btnVolverGestionCentrosComerciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverGestionCentrosComercialesActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(btnVolverGestionCentrosComerciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblTituloCentrosC.setBackground(new java.awt.Color(0, 102, 102));
        lblTituloCentrosC.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblTituloCentrosC.setForeground(new java.awt.Color(0, 102, 102));
        lblTituloCentrosC.setText("Gestion de Centros Comerciales");
        GestionCentrosComerciales.add(lblTituloCentrosC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        tablaCentrosComerciales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCentrosComerciales.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane5.setViewportView(tablaCentrosComerciales);

        GestionCentrosComerciales.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 500, 240));

        txtAreaConstruccionGestionCC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAreaConstruccionGestionCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaConstruccionGestionCCActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtAreaConstruccionGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 120, -1));

        lblAreaTerreno3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAreaTerreno3.setText("Area del terreno");
        GestionCentrosComerciales.add(lblAreaTerreno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        lblAreaConstruccion2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAreaConstruccion2.setText("Area de Construccion");
        GestionCentrosComerciales.add(lblAreaConstruccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        lblValorFiscal3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValorFiscal3.setText("Valor Fiscal");
        GestionCentrosComerciales.add(lblValorFiscal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        txtCantidadTiendas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadTiendasActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtCantidadTiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 70, -1));

        txtNumFincaGestionCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFincaGestionCCActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtNumFincaGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 120, -1));

        txtAreaTerrenoGestionCC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GestionCentrosComerciales.add(txtAreaTerrenoGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 120, -1));

        txtValorMetro2GestionCC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GestionCentrosComerciales.add(txtValorMetro2GestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 120, -1));

        txtValorFiscalGestionCC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorFiscalGestionCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorFiscalGestionCCActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtValorFiscalGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 120, -1));

        lblNumFincaGestionCC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumFincaGestionCC.setText("Numero de Finca");
        GestionCentrosComerciales.add(lblNumFincaGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        lblCantTiendas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCantTiendas.setText("Cantidad de tiendas");
        GestionCentrosComerciales.add(lblCantTiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lblEstilo3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstilo3.setText("Estilo Construccion");
        GestionCentrosComerciales.add(lblEstilo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        txtEspaciosGestionCC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEspaciosGestionCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspaciosGestionCCActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtEspaciosGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 120, -1));

        lblEspacios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEspacios.setText("Espacios/personas Mov. Red.");
        GestionCentrosComerciales.add(lblEspacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        lblModalidad3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModalidad3.setText("Modalidad");
        GestionCentrosComerciales.add(lblModalidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        txtCantidadSalasCines.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadSalasCines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadSalasCinesActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtCantidadSalasCines, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 70, -1));

        txtEstiloConstruccionGestionCC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstiloConstruccionGestionCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstiloConstruccionGestionCCActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtEstiloConstruccionGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 120, -1));

        txtModalidadGestionCC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModalidadGestionCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModalidadGestionCCActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtModalidadGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 120, -1));

        lblValorMetro6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValorMetro6.setText("Valor por metro cuadrado");
        GestionCentrosComerciales.add(lblValorMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        lblCantTiendas1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCantTiendas1.setText("Cantidad de salas de cine");
        GestionCentrosComerciales.add(lblCantTiendas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        lblCantTiendas2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCantTiendas2.setText("Cadena de Cine");
        GestionCentrosComerciales.add(lblCantTiendas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        txtCadenaCine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCadenaCine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadenaCineActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtCadenaCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 70, -1));

        lblCantHotspot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCantHotspot.setText("Cantidad de Hotspot WiFi");
        GestionCentrosComerciales.add(lblCantHotspot, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, -1));

        txtCantidadEscaleras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadEscaleras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadEscalerasActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtCantidadEscaleras, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 120, -1));

        lblCantEscaleras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCantEscaleras.setText("Cantidad de Escaleras");
        GestionCentrosComerciales.add(lblCantEscaleras, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        txtCantidadHotspot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadHotspot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadHotspotActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(txtCantidadHotspot, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 120, -1));

        btnRegresarGestionCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRegresarGestionCC.setText("Regresar al Menu");
        btnRegresarGestionCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarGestionCCActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(btnRegresarGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        btnSeleccionarGestionCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSeleccionarGestionCC.setText("Seleccionar");
        btnSeleccionarGestionCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarGestionCCActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(btnSeleccionarGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        btnModificarGestionCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnModificarGestionCC.setText("Modificar");
        btnModificarGestionCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarGestionCCActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(btnModificarGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        btnEliminarGestionCC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminarGestionCC.setText("Eliminar");
        btnEliminarGestionCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGestionCCActionPerformed(evt);
            }
        });
        GestionCentrosComerciales.add(btnEliminarGestionCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        panelprincipal.add(GestionCentrosComerciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, -1, -1));

        MostrarVentasPorProductoGerente_GUI.setMinimumSize(new java.awt.Dimension(850, 560));
        MostrarVentasPorProductoGerente_GUI.setPreferredSize(new java.awt.Dimension(850, 560));
        MostrarVentasPorProductoGerente_GUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarVentasPorProductoConsultar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMostrarVentasPorProductoConsultar.setText("Consultar");
        btnMostrarVentasPorProductoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVentasPorProductoConsultarActionPerformed(evt);
            }
        });
        MostrarVentasPorProductoGerente_GUI.add(btnMostrarVentasPorProductoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, 30));

        cboxMostrarProductosGerente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        MostrarVentasPorProductoGerente_GUI.add(cboxMostrarProductosGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 190, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Seleccione el producto");
        MostrarVentasPorProductoGerente_GUI.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        cbxcon2gertienda.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxcon2gertienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santa Cruz Bikes", "Rowlett Bikes" }));
        MostrarVentasPorProductoGerente_GUI.add(cbxcon2gertienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 190, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Seleccione la tienda:");
        MostrarVentasPorProductoGerente_GUI.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        txtcon2gerinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcon2gerinicioActionPerformed(evt);
            }
        });
        MostrarVentasPorProductoGerente_GUI.add(txtcon2gerinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 130, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Hasta:");
        MostrarVentasPorProductoGerente_GUI.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));
        MostrarVentasPorProductoGerente_GUI.add(txtcon2gerfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 130, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Desde:");
        MostrarVentasPorProductoGerente_GUI.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        jLabel23.setBackground(new java.awt.Color(0, 102, 102));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setText("Consultas por producto");
        MostrarVentasPorProductoGerente_GUI.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        btnMostrarVentasPorTiendaVolver1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMostrarVentasPorTiendaVolver1.setText("Volver");
        btnMostrarVentasPorTiendaVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVentasPorTiendaVolver1ActionPerformed(evt);
            }
        });
        MostrarVentasPorProductoGerente_GUI.add(btnMostrarVentasPorTiendaVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tablacon2ger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablacon2ger.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane4.setViewportView(tablacon2ger);

        MostrarVentasPorProductoGerente_GUI.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 560, 170));

        panelprincipal.add(MostrarVentasPorProductoGerente_GUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, -1, -1));

        MostrarVentasPorTiendaGerente_GUI.setMinimumSize(new java.awt.Dimension(850, 560));
        MostrarVentasPorTiendaGerente_GUI.setPreferredSize(new java.awt.Dimension(850, 560));
        MostrarVentasPorTiendaGerente_GUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarVentasPorTiendaVolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnMostrarVentasPorTiendaVolver.setText("Volver");
        btnMostrarVentasPorTiendaVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarVentasPorTiendaVolverActionPerformed(evt);
            }
        });
        MostrarVentasPorTiendaGerente_GUI.add(btnMostrarVentasPorTiendaVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel15.setBackground(new java.awt.Color(0, 102, 102));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Consultas por tiendas");
        MostrarVentasPorTiendaGerente_GUI.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Desde:");
        MostrarVentasPorTiendaGerente_GUI.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        MostrarVentasPorTiendaGerente_GUI.add(txtcon1gerentefin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 110, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Hasta:");
        MostrarVentasPorTiendaGerente_GUI.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));
        MostrarVentasPorTiendaGerente_GUI.add(txtcon1gerenteinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, -1));

        cboxtiendacon1gerente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cboxtiendacon1gerente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santa Cruz California", "Rowlett Texas" }));
        MostrarVentasPorTiendaGerente_GUI.add(cboxtiendacon1gerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 150, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Seleccione la tienda:");
        MostrarVentasPorTiendaGerente_GUI.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        btnVentasPorTiendaConsultar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnVentasPorTiendaConsultar.setText("Consultar");
        btnVentasPorTiendaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasPorTiendaConsultarActionPerformed(evt);
            }
        });
        MostrarVentasPorTiendaGerente_GUI.add(btnVentasPorTiendaConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        tablacon1gerente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablacon1gerente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(tablacon1gerente);

        MostrarVentasPorTiendaGerente_GUI.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 720, 210));

        panelprincipal.add(MostrarVentasPorTiendaGerente_GUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, -1, -1));

        PedidoPorRangoFechas_GUI.setMinimumSize(new java.awt.Dimension(850, 560));
        PedidoPorRangoFechas_GUI.setPreferredSize(new java.awt.Dimension(850, 560));
        PedidoPorRangoFechas_GUI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPedidoPorRangoFechasVolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnPedidoPorRangoFechasVolver.setText("Volver");
        btnPedidoPorRangoFechasVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoPorRangoFechasVolverActionPerformed(evt);
            }
        });
        PedidoPorRangoFechas_GUI.add(btnPedidoPorRangoFechasVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 102, 102));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Consultas por rango de fechas");
        PedidoPorRangoFechas_GUI.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Desde:");
        PedidoPorRangoFechas_GUI.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));
        PedidoPorRangoFechas_GUI.add(txtfechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 140, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Hasta:");
        PedidoPorRangoFechas_GUI.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));
        PedidoPorRangoFechas_GUI.add(txtfechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 140, -1));

        btnPedidoPorRangoFechaConsultar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnPedidoPorRangoFechaConsultar.setText("Consultar");
        btnPedidoPorRangoFechaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoPorRangoFechaConsultarActionPerformed(evt);
            }
        });
        PedidoPorRangoFechas_GUI.add(btnPedidoPorRangoFechaConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        tablaconsulta2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaconsulta2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tablaconsulta2);

        PedidoPorRangoFechas_GUI.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 660, 220));

        btnPedidoPorRangoLimpiar1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnPedidoPorRangoLimpiar1.setText("Limpiar");
        PedidoPorRangoFechas_GUI.add(btnPedidoPorRangoLimpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        panelprincipal.add(PedidoPorRangoFechas_GUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 0, -1, -1));

        getContentPane().add(panelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 850, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverGestionApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverGestionApartamentosActionPerformed
            Animacion.mover_derecha(0, 800, 5, 7, GestionApartamentos);
            Animacion.mover_derecha(-800, 0, 5, 7, GestionCasas);
    }//GEN-LAST:event_btnVolverGestionApartamentosActionPerformed

    private void btnMostrarVentasPorTiendaVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVentasPorTiendaVolverActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 7, GestionLotes);
        Animacion.mover_izquierda(0, -800, 5, 7, MostrarVentasPorTiendaGerente_GUI);
    }//GEN-LAST:event_btnMostrarVentasPorTiendaVolverActionPerformed

    private void btnMostrarVentasPorTiendaVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVentasPorTiendaVolver1ActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 7, GestionCasas);
        Animacion.mover_izquierda(0, -800, 5, 7, MostrarVentasPorProductoGerente_GUI);
    }//GEN-LAST:event_btnMostrarVentasPorTiendaVolver1ActionPerformed

    private void txtcon2gerinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcon2gerinicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcon2gerinicioActionPerformed
    public void resultset(String consulta, int opcion) throws SQLException {
        /*ConectarCentral obj = new ConectarCentral();
        ResultSet r;
        r = obj.Listar(consulta);
        while (r.next()) {
            switch (opcion) {
                case 1:
                    cboxproducto.addItem(r.getString(1));
                    break;                    
                case 3:
                    cbxcatcon4.addItem(r.getString(1));
                    break;
                case 4:
                    cboxempleado.addItem(r.getString(1));
                    break;
                case 5:
                    cbxcliente.addItem(r.getString(1));
                    break;
            }
      
         }
     } */
    /*public void resultset2(String consulta) throws SQLException{
        ConectarCentral obj = new ConectarCentral();
        ResultSet r;
        r = obj.Listar(consulta);
        while(r.next()){
            cboxMostrarProductosGerente.addItem(r.getString(1));           
        }
    }
          
    public void cargar_cbxcategorias(){
        cbxcatcon4.removeAll();
        String strl = "select * from cbxcategorias";
        try {
            resultset(strl, 3);
        } catch (Exception e) {
        }
    }
    public void cargar_cbxproductos_tienda(){
        String strl = "";
        if(sede.equals("Sede California")){
           strl = "select * from cbxproductosCalifornia";  
        }else{
           strl = "select * from cbxproductosTexas";
        }        
        try {
            resultset(strl,1);
        } catch (Exception e) {
        }
    }
    
    public void cargar_cbxproductoscentral(){
        String strl = "select * from cbxproductos";
        try {
            resultset2(strl);
        } catch (Exception e) {
        }
    }
    
    
    
    public void cargar_cbxempleados(){
        String strl= "";
        if(sede.equals("Sede California")){
           strl = "select * from cbxempleadosCalifornia";  
        }else{
           strl = "select * from cbxempleadosTexas";
        }
        try {
            resultset(strl, 4);
        } catch (Exception e) {
        }                
    }
    
    public void cargar_cbxclientes(){      
        String strl = "";
        if(sede.equals("Sede California")){
            strl = "select * from cbxclientesCalifornia";
        }else{
            strl = "select * from cbxclientesTexas";
        }
        try {
            resultset(strl, 5);
        } catch (Exception e) {
        }   
    }
    
    public int obtener_id_producto(String producto_seleccionado) throws SQLException{
        int idproducto=0;
        String producto_vista;
        ResultSet r;
        String consulta = "SELECT * FROM vistaproductos";
        ConectarCentral obj = new ConectarCentral();
        r = obj.Listar(consulta);
        while (r.next()) {
            idproducto = Integer.parseInt(r.getString(1));
            producto_vista = r.getString(2);
            if (producto_vista.equals(producto_seleccionado)) {
                return idproducto;
            }
        }
        return idproducto;            
    }
       
    public int obtener_id_cliente(String cliente_seleccionado,String sede) throws SQLException{
        int idcliente = 0;
        String cliente_vista;
        ResultSet r;
        String consulta = "";
        if(sede.equals("Sede California")){
            consulta = "SELECT * FROM vistaclientescalifornia";          
        }else{
            consulta = "SELECT * FROM vistaclientestexas"; 
        }
        ConectarCentral obj = new ConectarCentral();
        r = obj.Listar(consulta);
        while(r.next()){
            idcliente = Integer.parseInt(r.getString(1));
            cliente_vista = r.getString(2);
            if(cliente_vista.equals(cliente_seleccionado)){
                return idcliente;               
            }                    
        }
        return idcliente;
    }
    
    public int obtener_id_empleado(String empleado_seleccionado) throws SQLException{
        int idempleado = 0;
        String empleado_vista;
        ResultSet r;
        String consulta = "select * from vistaempleados";
        ConectarCentral obj = new ConectarCentral();
        r = obj.Listar(consulta);
        while(r.next()){
            idempleado = Integer.parseInt(r.getString(1));
            empleado_vista = r.getString(2);
            if(empleado_vista.equals(empleado_seleccionado)){
                return idempleado;
            }
        }
        return idempleado;
    }*/
    
    
//    public void limpiar_tablaconsulta2(){
       tablaconsulta2.removeAll();
    }
    
    public void limpiar_tablaadmin(){
        tablaApartamentos.removeAll();
    }

    private void btnVolverGestionCentrosComercialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverGestionCentrosComercialesActionPerformed
        Animacion.mover_derecha(0, 800, 5, 7, GestionCentrosComerciales);
        Animacion.mover_derecha(-800, 0, 5, 7, GestionApartamentos); 
    }//GEN-LAST:event_btnVolverGestionCentrosComercialesActionPerformed

    private void btnVolverGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverGestionCasasActionPerformed
        Animacion.mover_derecha(0, 800, 5, 7, GestionCasas);
        Animacion.mover_derecha(-800, 0, 5, 7, GestionLotes);
    }//GEN-LAST:event_btnVolverGestionCasasActionPerformed

    private void btnVentasPorTiendaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasPorTiendaConsultarActionPerformed
       /* int idTienda=0;
        if(txtcon1gerenteinicio.getText().equals("") || txtcon1gerentefin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "EL CAMPO NO PUEDE ESTAR VACIO");
        }else{
            if(cboxtiendacon1gerente.getSelectedItem().equals("Santa Cruz California")){
                idTienda = 1;
            }else{
                idTienda = 3;
            }
            consulta1_gerente tabla_consulta1_gerente = new consulta1_gerente();
            tabla_consulta1_gerente.visualizar_consulta1(tablacon1gerente, txtcon1gerenteinicio.getText(), txtcon1gerentefin.getText(), idTienda);
        }*/
        
    }//GEN-LAST:event_btnVentasPorTiendaConsultarActionPerformed

    private void btnMostrarVentasPorProductoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarVentasPorProductoConsultarActionPerformed
       /* if(txtcon2gerinicio.getText().equals("") || txtcon2gerfin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "EL CAMPO NO PUEDE ESTAR VACIO");
        }else{
            consulta2_gerente tabla_consulta2_gerente = new consulta2_gerente();
            tabla_consulta2_gerente.visualizar_consulta2(tablacon2ger, txtcon2gerinicio.getText(), txtcon2gerfin.getText(), cbxcon2gertienda.getSelectedItem().toString(),cboxMostrarProductosGerente.getSelectedItem().toString());
        }  */     
    }//GEN-LAST:event_btnMostrarVentasPorProductoConsultarActionPerformed

    private void txtValorFiscalGestionLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFiscalGestionLotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFiscalGestionLotesActionPerformed

    private void txtModalidadGestionLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModalidadGestionLotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModalidadGestionLotesActionPerformed

    private void btnVerCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCasasActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 10, GestionCasas);
        Animacion.mover_izquierda(0, -800, 5, 10, GestionLotes );
    }//GEN-LAST:event_btnVerCasasActionPerformed

    private void txtAreaConstruccionGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaConstruccionGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaConstruccionGestionCasasActionPerformed

    private void txtCantidadNivelesGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadNivelesGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadNivelesGestionCasasActionPerformed

    private void txtNumFincaGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFincaGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFincaGestionCasasActionPerformed

    private void txtValorFiscalGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFiscalGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFiscalGestionCasasActionPerformed

    private void txtAnioConstruccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioConstruccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioConstruccionActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtEstiloConstruccionGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstiloConstruccionGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstiloConstruccionGestionCasasActionPerformed

    private void txtModalidadGestionCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModalidadGestionCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModalidadGestionCasasActionPerformed

    private void btnVerApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerApartamentosActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 10, GestionApartamentos);
        Animacion.mover_izquierda(0, -800, 5, 10, GestionCasas );
    }//GEN-LAST:event_btnVerApartamentosActionPerformed

    private void btnVolverGestionLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverGestionLotesActionPerformed
        MenuAgentesFrame ventana = new MenuAgentesFrame();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverGestionLotesActionPerformed

    private void txtAreaConstruccionGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaConstruccionGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaConstruccionGestionCasas1ActionPerformed

    private void txtCantidadNivelesGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadNivelesGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadNivelesGestionCasas1ActionPerformed

    private void txtNumFincaGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFincaGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFincaGestionCasas1ActionPerformed

    private void txtValorFiscalGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFiscalGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFiscalGestionCasas1ActionPerformed

    private void txtAnioConstruccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioConstruccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioConstruccion1ActionPerformed

    private void txtColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColor1ActionPerformed

    private void txtEstiloConstruccionGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstiloConstruccionGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstiloConstruccionGestionCasas1ActionPerformed

    private void txtModalidadGestionCasas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModalidadGestionCasas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModalidadGestionCasas1ActionPerformed

    private void btnVerCentrosComercialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCentrosComercialesActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 10, GestionCentrosComerciales);
        Animacion.mover_izquierda(0, -800, 5, 10, GestionApartamentos );
    }//GEN-LAST:event_btnVerCentrosComercialesActionPerformed

    private void btnSeleccionarGestionApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarGestionApartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarGestionApartamentosActionPerformed

    private void btnModificarGestionApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarGestionApartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarGestionApartamentosActionPerformed

    private void btnEliminarGestionApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGestionApartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarGestionApartamentosActionPerformed

    private void txtAreaConstruccionGestionCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaConstruccionGestionCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaConstruccionGestionCCActionPerformed

    private void txtCantidadTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadTiendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadTiendasActionPerformed

    private void txtNumFincaGestionCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFincaGestionCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFincaGestionCCActionPerformed

    private void txtValorFiscalGestionCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFiscalGestionCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFiscalGestionCCActionPerformed

    private void txtEspaciosGestionCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspaciosGestionCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspaciosGestionCCActionPerformed

    private void txtCantidadSalasCinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadSalasCinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadSalasCinesActionPerformed

    private void txtEstiloConstruccionGestionCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstiloConstruccionGestionCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstiloConstruccionGestionCCActionPerformed

    private void txtModalidadGestionCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModalidadGestionCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModalidadGestionCCActionPerformed

    private void txtCadenaCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadenaCineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadenaCineActionPerformed

    private void txtCantidadEscalerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadEscalerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadEscalerasActionPerformed

    private void txtCantidadHotspotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadHotspotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadHotspotActionPerformed

    private void btnRegresarGestionCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarGestionCCActionPerformed
        MenuAgentesFrame ventana = new MenuAgentesFrame();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarGestionCCActionPerformed

    private void btnSeleccionarGestionCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarGestionCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarGestionCCActionPerformed

    private void btnModificarGestionCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarGestionCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarGestionCCActionPerformed

    private void btnEliminarGestionCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGestionCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarGestionCCActionPerformed

    private void btnPedidoPorRangoFechaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoPorRangoFechaConsultarActionPerformed
        /* limpiar_tablaconsulta2();
        if(txtfechainicio.getText().equals("") || txtfechafin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "EL CAMPO NO PUEDE ESTAR VACIO");
        }else{
            consulta2 tabla_consulta2 = new consulta2();
            tabla_consulta2.visualizar_consulta2(tablaconsulta2,txtfechainicio.getText(),txtfechafin.getText(),sede);
        }  */
    }//GEN-LAST:event_btnPedidoPorRangoFechaConsultarActionPerformed

    private void btnPedidoPorRangoFechasVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoPorRangoFechasVolverActionPerformed
        Animacion.mover_izquierda(800, 0, 5, 7, GestionApartamentos);
        Animacion.mover_izquierda(0, -800, 5, 7, PedidoPorRangoFechas_GUI);
    }//GEN-LAST:event_btnPedidoPorRangoFechasVolverActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCatalogoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GestionApartamentos;
    private javax.swing.JPanel GestionCasas;
    private javax.swing.JPanel GestionCentrosComerciales;
    private javax.swing.JPanel GestionLotes;
    private javax.swing.JPanel MostrarVentasPorProductoGerente_GUI;
    private javax.swing.JPanel MostrarVentasPorTiendaGerente_GUI;
    private javax.swing.JPanel PedidoPorRangoFechas_GUI;
    public javax.swing.JToggleButton btnAdminLimpiar1;
    public javax.swing.JToggleButton btnEliminarGestionApartamentos;
    public javax.swing.JToggleButton btnEliminarGestionCC;
    public javax.swing.JToggleButton btnEliminarGestionCasas;
    private javax.swing.JButton btnEliminarGestionLotes;
    public javax.swing.JToggleButton btnLimpiarGestionCasas;
    public javax.swing.JToggleButton btnModificarGestionApartamentos;
    public javax.swing.JToggleButton btnModificarGestionCC;
    public javax.swing.JToggleButton btnModificarGestionCasas;
    private javax.swing.JButton btnModificarGestionLotes;
    public javax.swing.JToggleButton btnMostrarVentasPorProductoConsultar;
    public javax.swing.JToggleButton btnMostrarVentasPorTiendaVolver;
    public javax.swing.JToggleButton btnMostrarVentasPorTiendaVolver1;
    private javax.swing.JToggleButton btnPedidoPorRangoFechaConsultar;
    private javax.swing.JToggleButton btnPedidoPorRangoFechasVolver;
    private javax.swing.JToggleButton btnPedidoPorRangoLimpiar1;
    public javax.swing.JToggleButton btnRegresarGestionCC;
    public javax.swing.JToggleButton btnSeleccionarGestionApartamentos;
    public javax.swing.JToggleButton btnSeleccionarGestionCC;
    public javax.swing.JToggleButton btnSeleccionarGestionCasas;
    private javax.swing.JButton btnSeleccionarGestionLotes;
    public javax.swing.JToggleButton btnVentasPorTiendaConsultar;
    public javax.swing.JToggleButton btnVerApartamentos;
    private javax.swing.JButton btnVerCasas;
    public javax.swing.JToggleButton btnVerCentrosComerciales;
    public javax.swing.JToggleButton btnVolverGestionApartamentos;
    public javax.swing.JToggleButton btnVolverGestionCasas;
    public javax.swing.JToggleButton btnVolverGestionCentrosComerciales;
    private javax.swing.JButton btnVolverGestionLotes;
    public javax.swing.JComboBox<String> cboxMostrarProductosGerente;
    public javax.swing.JComboBox<String> cboxtiendacon1gerente;
    public javax.swing.JComboBox<String> cbxcon2gertienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblAreaConstruccion;
    private javax.swing.JLabel lblAreaConstruccion1;
    private javax.swing.JLabel lblAreaConstruccion2;
    private javax.swing.JLabel lblAreaTerreno;
    private javax.swing.JLabel lblAreaTerreno1;
    private javax.swing.JLabel lblAreaTerreno2;
    private javax.swing.JLabel lblAreaTerreno3;
    private javax.swing.JLabel lblAñoConstruccion;
    private javax.swing.JLabel lblAñoConstruccion1;
    private javax.swing.JLabel lblCantEscaleras;
    private javax.swing.JLabel lblCantHotspot;
    private javax.swing.JLabel lblCantNiveles;
    private javax.swing.JLabel lblCantNiveles1;
    private javax.swing.JLabel lblCantTiendas;
    private javax.swing.JLabel lblCantTiendas1;
    private javax.swing.JLabel lblCantTiendas2;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEspacios;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblEstilo1;
    private javax.swing.JLabel lblEstilo2;
    private javax.swing.JLabel lblEstilo3;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblModalidad1;
    private javax.swing.JLabel lblModalidad2;
    private javax.swing.JLabel lblModalidad3;
    private javax.swing.JLabel lblNumFinca;
    private javax.swing.JLabel lblNumFinca1;
    private javax.swing.JLabel lblNumFinca2;
    private javax.swing.JLabel lblNumFincaGestionCC;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTituloCentrosC;
    private javax.swing.JLabel lblValorFiscal;
    private javax.swing.JLabel lblValorFiscal1;
    private javax.swing.JLabel lblValorFiscal2;
    private javax.swing.JLabel lblValorFiscal3;
    private javax.swing.JLabel lblValorMetro2;
    private javax.swing.JLabel lblValorMetro3;
    private javax.swing.JLabel lblValorMetro4;
    private javax.swing.JLabel lblValorMetro6;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JTable tablaApartamentos;
    private javax.swing.JTable tablaCasas;
    private javax.swing.JTable tablaCentrosComerciales;
    private javax.swing.JTable tablaLotes;
    private javax.swing.JTable tablacon1gerente;
    private javax.swing.JTable tablacon2ger;
    private javax.swing.JTable tablaconsulta2;
    private javax.swing.JTextField txtAnioConstruccion;
    private javax.swing.JTextField txtAnioConstruccion1;
    private javax.swing.JTextField txtAreaConstruccionGestionCC;
    private javax.swing.JTextField txtAreaConstruccionGestionCasas;
    private javax.swing.JTextField txtAreaConstruccionGestionCasas1;
    private javax.swing.JTextField txtAreaTerrenoGestionCC;
    private javax.swing.JTextField txtAreaTerrenoGestionCasas;
    private javax.swing.JTextField txtAreaTerrenoGestionCasas1;
    private javax.swing.JTextField txtAreaTerrenoGestionLotes;
    private javax.swing.JTextField txtCadenaCine;
    private javax.swing.JTextField txtCantidadEscaleras;
    private javax.swing.JTextField txtCantidadHotspot;
    private javax.swing.JTextField txtCantidadNivelesGestionCasas;
    private javax.swing.JTextField txtCantidadNivelesGestionCasas1;
    private javax.swing.JTextField txtCantidadSalasCines;
    private javax.swing.JTextField txtCantidadTiendas;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtColor1;
    private javax.swing.JTextField txtEspaciosGestionCC;
    private javax.swing.JTextField txtEstiloConstruccionGestionCC;
    private javax.swing.JTextField txtEstiloConstruccionGestionCasas;
    private javax.swing.JTextField txtEstiloConstruccionGestionCasas1;
    private javax.swing.JTextField txtModalidadGestionCC;
    private javax.swing.JTextField txtModalidadGestionCasas;
    private javax.swing.JTextField txtModalidadGestionCasas1;
    private javax.swing.JTextField txtModalidadGestionLotes;
    private javax.swing.JTextField txtNumFincaGestionCC;
    private javax.swing.JTextField txtNumFincaGestionCasas;
    private javax.swing.JTextField txtNumFincaGestionCasas1;
    private javax.swing.JTextField txtNumFincaGestionLotes;
    private javax.swing.JTextField txtValorFiscalGestionCC;
    private javax.swing.JTextField txtValorFiscalGestionCasas;
    private javax.swing.JTextField txtValorFiscalGestionCasas1;
    private javax.swing.JTextField txtValorFiscalGestionLotes;
    private javax.swing.JTextField txtValorMetro2GestionCC;
    private javax.swing.JTextField txtValorMetro2GestionCasas;
    private javax.swing.JTextField txtValorMetro2GestionCasas1;
    private javax.swing.JTextField txtValorMetro2GestionLotes;
    public javax.swing.JTextField txtcon1gerentefin;
    public javax.swing.JTextField txtcon1gerenteinicio;
    public javax.swing.JTextField txtcon2gerfin;
    public javax.swing.JTextField txtcon2gerinicio;
    private javax.swing.JTextField txtfechafin;
    private javax.swing.JTextField txtfechainicio;
    // End of variables declaration//GEN-END:variables
}
