/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.tipoPropiedadFrame;

/**
 *
 * @author USUARIO
 */
public class RegistrarNuevoCentroComercial extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarNuevoApartamento
     */
    public RegistrarNuevoCentroComercial() {
        initComponents();
        
        cbxModalidad.addItem("Venta");
        cbxModalidad.addItem("Alquiler");
        
        cbxProvincias.addItem("San Jose");
        cbxProvincias.addItem("Cartago");
        cbxProvincias.addItem("Alajuela");
        cbxProvincias.addItem("Heredia");
        cbxProvincias.addItem("Pintarenas");
        cbxProvincias.addItem("Guanacaste");
        cbxProvincias.addItem("Limon");
        
        cbxEstilo.addItem("Gotico");
        cbxEstilo.addItem("Contemporaneo");
        cbxEstilo.addItem("Barroco");
        cbxEstilo.addItem("Modernista");
        cbxEstilo.addItem("Art-Deco");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNumFinca = new javax.swing.JLabel();
        lblAreaTerreno = new javax.swing.JLabel();
        lblValorMetro2 = new javax.swing.JLabel();
        lblValorFiscal = new javax.swing.JLabel();
        txtNumFinca = new javax.swing.JTextField();
        txtValorMetro2 = new javax.swing.JTextField();
        txtAreaTerreno = new javax.swing.JTextField();
        txtValorFiscal = new javax.swing.JTextField();
        lblAreaConstruccion = new javax.swing.JLabel();
        lblProvincias = new javax.swing.JLabel();
        lblDistrito = new javax.swing.JLabel();
        lblCanton = new javax.swing.JLabel();
        txtlZonasPersonasReducidas = new javax.swing.JTextField();
        cbxProvincias = new javax.swing.JComboBox<>();
        txtCanton = new javax.swing.JTextField();
        txtDistrito = new javax.swing.JTextField();
        lblCantTiendas = new javax.swing.JLabel();
        txtCantidadTiendas = new javax.swing.JTextField();
        lblEstilo = new javax.swing.JLabel();
        lblCantCine = new javax.swing.JLabel();
        txtCadenaCines = new javax.swing.JTextField();
        btnAgregarImagen = new javax.swing.JButton();
        lblCadenaCines = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        txtCantidadSalas = new javax.swing.JTextField();
        lblZonasPersonasReducidas = new javax.swing.JLabel();
        txtAreaConstruccion = new javax.swing.JTextField();
        cbxEstilo = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUbicacion = new javax.swing.JTextArea();
        btnSiguiente = new javax.swing.JButton();
        lblModalidad = new javax.swing.JLabel();
        cbxModalidad = new javax.swing.JComboBox<>();
        lblCantHotspot = new javax.swing.JLabel();
        txtCantidadEscaleras = new javax.swing.JTextField();
        lblCantEscaleras = new javax.swing.JLabel();
        txtCantidadHotspot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblTitulo.setText("Registro de Nuevo Centro Comercial");

        lblNumFinca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumFinca.setText("Numero de Finca");

        lblAreaTerreno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaTerreno.setText("Area del Terreno");

        lblValorMetro2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorMetro2.setText("Valor por metro cuadrado");

        lblValorFiscal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValorFiscal.setText("Valor Fiscal");

        txtNumFinca.setToolTipText("");

        txtValorMetro2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAreaTerreno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtValorFiscal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblAreaConstruccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaConstruccion.setText("Area de Construccion");

        lblProvincias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProvincias.setText("Provincia");

        lblDistrito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDistrito.setText("Distrito");

        lblCanton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCanton.setText("Canton");

        txtlZonasPersonasReducidas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDistrito.setToolTipText("");

        lblCantTiendas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantTiendas.setText("Cantidad de Tiendas");

        lblEstilo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstilo.setText("Estilo de Construccion");

        lblCantCine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantCine.setText("Cantidad de Salas de Cine");

        txtCadenaCines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadenaCinesActionPerformed(evt);
            }
        });

        btnAgregarImagen.setText("Adjuntar Imagen...");
        btnAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImagenActionPerformed(evt);
            }
        });

        lblCadenaCines.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCadenaCines.setText("Cadena de Cines");

        lblUbicacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUbicacion.setText("Ubicacion Exacta");

        lblZonasPersonasReducidas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblZonasPersonasReducidas.setText("Espacios para personas con movilidad reducida");

        txtAreaConstruccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtUbicacion.setColumns(20);
        txtUbicacion.setRows(5);
        jScrollPane2.setViewportView(txtUbicacion);

        btnSiguiente.setText("Registrar");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblModalidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModalidad.setText("Modalidad");

        cbxModalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModalidadActionPerformed(evt);
            }
        });

        lblCantHotspot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantHotspot.setText("Cantidad de Hotspot WiFi");

        txtCantidadEscaleras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadEscaleras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadEscalerasActionPerformed(evt);
            }
        });

        lblCantEscaleras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantEscaleras.setText("Cantidad de Escaleras");

        txtCantidadHotspot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadHotspot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadHotspotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtNumFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(txtAreaTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblAreaConstruccion)
                        .addGap(143, 143, 143)
                        .addComponent(lblProvincias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblNumFinca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAreaTerreno)
                        .addGap(82, 82, 82)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValorMetro2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblValorFiscal)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtValorMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(txtValorFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(lblCanton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDistrito)
                                    .addGap(60, 60, 60))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCantidadSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(txtCadenaCines)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantCine)
                                .addGap(72, 72, 72)
                                .addComponent(lblCadenaCines)
                                .addGap(26, 26, 26)))
                        .addGap(16, 16, 16))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblEstilo)
                        .addGap(103, 103, 103)
                        .addComponent(lblCantTiendas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAreaConstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUbicacion))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCantidadTiendas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxProvincias, javax.swing.GroupLayout.Alignment.LEADING, 0, 172, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblZonasPersonasReducidas)
                        .addGap(18, 18, 18)
                        .addComponent(lblCantHotspot)
                        .addGap(56, 56, 56)
                        .addComponent(lblCantEscaleras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblModalidad)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtlZonasPersonasReducidas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtCantidadHotspot, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtCantidadEscaleras, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumFinca)
                    .addComponent(lblAreaTerreno)
                    .addComponent(lblValorMetro2)
                    .addComponent(lblValorFiscal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumFinca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAreaTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAreaConstruccion)
                    .addComponent(lblProvincias)
                    .addComponent(lblDistrito)
                    .addComponent(lblCanton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAreaConstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantTiendas)
                    .addComponent(lblEstilo)
                    .addComponent(lblCantCine)
                    .addComponent(lblCadenaCines))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadenaCines, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(lblUbicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZonasPersonasReducidas)
                    .addComponent(lblModalidad)
                    .addComponent(lblCantHotspot)
                    .addComponent(lblCantEscaleras))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlZonasPersonasReducidas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadEscaleras, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadHotspot, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarImagenActionPerformed

    private void txtCadenaCinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadenaCinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadenaCinesActionPerformed

    private void cbxModalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxModalidadActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        RegistrarNuevoNivelApartamento ventana = new RegistrarNuevoNivelApartamento();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtCantidadEscalerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadEscalerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadEscalerasActionPerformed

    private void txtCantidadHotspotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadHotspotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadHotspotActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        tipoPropiedadFrame ventana = new tipoPropiedadFrame();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarNuevoCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarNuevoCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarNuevoCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarNuevoCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarNuevoCentroComercial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarImagen;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxEstilo;
    private javax.swing.JComboBox<String> cbxModalidad;
    private javax.swing.JComboBox<String> cbxProvincias;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAreaConstruccion;
    private javax.swing.JLabel lblAreaTerreno;
    private javax.swing.JLabel lblCadenaCines;
    private javax.swing.JLabel lblCantCine;
    private javax.swing.JLabel lblCantEscaleras;
    private javax.swing.JLabel lblCantHotspot;
    private javax.swing.JLabel lblCantTiendas;
    private javax.swing.JLabel lblCanton;
    private javax.swing.JLabel lblDistrito;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblNumFinca;
    private javax.swing.JLabel lblProvincias;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblValorFiscal;
    private javax.swing.JLabel lblValorMetro2;
    private javax.swing.JLabel lblZonasPersonasReducidas;
    private javax.swing.JTextField txtAreaConstruccion;
    private javax.swing.JTextField txtAreaTerreno;
    private javax.swing.JTextField txtCadenaCines;
    private javax.swing.JTextField txtCantidadEscaleras;
    private javax.swing.JTextField txtCantidadHotspot;
    private javax.swing.JTextField txtCantidadSalas;
    private javax.swing.JTextField txtCantidadTiendas;
    private javax.swing.JTextField txtCanton;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtNumFinca;
    private javax.swing.JTextArea txtUbicacion;
    private javax.swing.JTextField txtValorFiscal;
    private javax.swing.JTextField txtValorMetro2;
    private javax.swing.JTextField txtlZonasPersonasReducidas;
    // End of variables declaration//GEN-END:variables
}
