
package Vista;

import Modelo.Apartamento;
import Modelo.Casa;
import Modelo.CentroComercial;
import Modelo.Lote;
import Modelo.Nivel;
import controlador.ControladorPropiedad;

/**
 *
 * @author USUARIO
 */
public class tipoPropiedadFrame extends javax.swing.JFrame {

    /**
     * Creates new form tipoPropiedadFrame
     */
    public tipoPropiedadFrame() {
        initComponents();
        
        cbxTipoPropiedad.addItem("Lote");
        cbxTipoPropiedad.addItem("Casa");
        cbxTipoPropiedad.addItem("Apartamento");
        cbxTipoPropiedad.addItem("Centro Comercial");
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeleccionar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        cbxTipoPropiedad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSeleccionar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        cbxTipoPropiedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbxTipoPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoPropiedadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione el tipo de propiedad que desea registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSeleccionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(cbxTipoPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbxTipoPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnSeleccionar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuAgentesFrame ventana = new MenuAgentesFrame();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void cbxTipoPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoPropiedadActionPerformed
        // TODO add your handling code here:
        int selection = cbxTipoPropiedad.getSelectedIndex();
        Lote lote = new Lote();
        Casa casa = new Casa();
        Apartamento aparta = new Apartamento();
        Nivel nivel = new Nivel();
        CentroComercial cc = new CentroComercial();
        
        RegistrarNuevoLoteFrame frmRegistrarLote = new RegistrarNuevoLoteFrame();
        RegistrarNuevaCasaFrame frmRegistrarCasa = new RegistrarNuevaCasaFrame();
        RegistrarNuevoApartamento frmRegistrarApartamento = new RegistrarNuevoApartamento();
        RegistrarNuevoCentroComercial frmRegistrarCentroC = new RegistrarNuevoCentroComercial();
        RegistrarNuevoNivelApartamento frmRegistrarNivelAparta = new RegistrarNuevoNivelApartamento();
        ConsultaBienes consulta = new ConsultaBienes();
        
            switch (selection) {
                case 0:
                   break;
                case 1:
                    ControladorPropiedad controladorL = new ControladorPropiedad(lote, casa, aparta, cc, frmRegistrarLote, frmRegistrarCasa, frmRegistrarApartamento, frmRegistrarCentroC, frmRegistrarNivelAparta,nivel, consulta);
                    frmRegistrarLote.setVisible(true);
                    this.dispose();
                    break;
                case 2: 
                    ControladorPropiedad controladorC = new ControladorPropiedad(lote, casa, aparta, cc, frmRegistrarLote, frmRegistrarCasa, frmRegistrarApartamento, frmRegistrarCentroC, frmRegistrarNivelAparta,nivel, consulta);
                    frmRegistrarCasa.setVisible(true);
                    this.dispose();
                    break;
                case 3:
                    ControladorPropiedad controladorA = new ControladorPropiedad(lote, casa, aparta, cc, frmRegistrarLote, frmRegistrarCasa, frmRegistrarApartamento, frmRegistrarCentroC, frmRegistrarNivelAparta,nivel, consulta);
                    frmRegistrarApartamento.setVisible(true);
                    this.dispose();
                    break;
                case 4:
                    ControladorPropiedad controladorCC = new ControladorPropiedad(lote, casa, aparta, cc, frmRegistrarLote, frmRegistrarCasa, frmRegistrarApartamento, frmRegistrarCentroC, frmRegistrarNivelAparta,nivel, consulta);
                    frmRegistrarCentroC.setVisible(true);
                    this.dispose();
                    break;    
                    
                                   
                default:
                    break;
            }
     
    }//GEN-LAST:event_cbxTipoPropiedadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tipoPropiedadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tipoPropiedadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tipoPropiedadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tipoPropiedadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tipoPropiedadFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxTipoPropiedad;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
